Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2018-03, with the labels that each got.

#1003 Use relative time for checking if time is within range
  src/main.cpp
  src/test/util_tests.cpp
  src/util.cpp
  src/util.h
  src/wallet.cpp
Labels: bug

#1010 Removes unnecessary lsn_reset from CheckpointLSN to improve wallet performance
  src/backup.cpp
  src/db.cpp
  src/db.h
  src/walletdb.cpp
Labels: enhancement, help wanted

#1018 Runtime hickups
  src/init.cpp
  src/main.cpp
  src/wallet.cpp
Labels: enhancement
