Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2019-03, with the labels that each got.

#1409 Re-activate Windows Installer
  Makefile.am
  share/pixmaps/gridcoin-bc.ico
  share/pixmaps/gridcoin.ico
  share/pixmaps/gridcoin.png
  share/pixmaps/gridcoin128.png
  share/pixmaps/gridcoin16.ico
  share/pixmaps/gridcoin256.png
  share/pixmaps/gridcoin32.ico
  share/pixmaps/gridcoin32.png
  share/pixmaps/gridcoin64.ico
  share/setup.nsi.in
Labels: Build System

#1416 Change dumpwallet to use appropriate data directory
  src/rpcdump.cpp
Labels: bug

#1417 Build fixes for ARM and incorrect icon file.
  Makefile.am
  depends/packages/bdb53.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/qt59.mk
  depends/packages/xextproto.mk
Labels: Build System

#1418 Add automatic wallet backup to advertisebeacon
  src/rpcblockchain.cpp
Labels: enhancement

#1402 Remove auto unlock.
  src/crypter.cpp
  src/crypter.h
  src/main.cpp
  src/miner.cpp
  src/test/crypter_tests.cpp
Labels: enhancement
