Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-04, with the labels that each got.

#1660 Update openssl to 1.1.1f
  depends/packages/openssl.mk
Labels: compatibility

#1659 Optimize bdb to avoid synchronous flush of database
  src/db.cpp
  src/db.h
  src/test/accounting_tests.cpp
  src/wallet.cpp
  src/wallet.h
  src/walletdb.cpp
  src/walletdb.h
Labels: enhancement

#1662 Publish example gridcoinresearch.conf as a md document to the doc directory
  doc/gridcoinresearch.conf.md
Labels: Documentation

#1665 Remove qt5.7.1 depends support
  depends/Makefile
  depends/README.md
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/patches/qt/fix-xcb-include-order.patch
  depends/patches/qt/fix_qt_pkgconfig.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/qt/mingw-uuidof.patch
  depends/patches/qt/pidlist_absolute.patch
Labels: Build System

#1666 Add options checkbox to disable transaction notifications
  src/qt/bitcoingui.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: enhancement
