Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-09, with the labels that each got.

#1859 build: Add support for building with musl and Alpine Linux
  depends/config.guess
  depends/packages/fontconfig.mk
  depends/patches/fontconfig/0001-Avoid-conflicts-with-integer-width-macros-from-TS-18.patch
  doc/assets-attribution.md
  doc/build-unix.md
  gridcoinresearch.pro
  src/Makefile.am
  src/compat.h
  src/netbase.cpp
  src/strlcpy.h
  src/util.cpp
Labels: build System, compatibility

#1860 gui: Fix researcher wizard layout on macOS with native theme
  src/qt/forms/researcherwizard.ui
  src/qt/forms/researcherwizardinvestorpage.ui
  src/qt/forms/researcherwizardmodepage.ui
  src/qt/forms/researcherwizardpoolpage.ui
  src/qt/forms/researcherwizardpoolsummarypage.ui
  src/qt/forms/researcherwizardprojectspage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/votingdialog.cpp
Labels: enhancement, gui

#1862 consensus: Set block version 11 threshold height for mainnet
  src/main.h
Labels: mandatory

#1863 build: Tweak Gridcoin installer for Fern release
  share/pixmaps/gridcoin_testnet.ico
  share/setup.nsi.in
  src/Makefile.qt.include
  src/qt/res/gridcoinresearch.rc
  src/qt/res/icons/gridcoin_testnet.ico
Labels: bug, enhancement

#1866 build: Add support for building with musl and Alpine Linux (rebase)
  depends/config.guess
  depends/packages/fontconfig.mk
  depends/patches/fontconfig/0001-Avoid-conflicts-with-integer-width-macros-from-TS-18.patch
  doc/assets-attribution.md
  doc/build-unix.md
  gridcoinresearch.pro
  src/Makefile.am
  src/compat.h
  src/netbase.cpp
  src/strlcpy.h
  src/util.cpp
Labels: build System, compatibility

#1867 test, ci: xenial support
  .travis.yml
  ci/test/00_setup_env_native_old.sh
  src/test/neuralnet/researcher_tests.cpp
Labels: compatibility

#1869 Fix compatibility with Boost 1.74
  src/backup.cpp
Labels: compatibility

#1870 test: Fix tests for _GLIBCXX_ASSERTIONS
  src/script.cpp
  src/test/base58_tests.cpp
  src/test/script_tests.cpp
Labels: compatibility

#1871 Fix Windows API for default data directory with wide characters
  src/util.cpp
Labels: bug, compatibility

#1873 gui: Fix OP_RETURN filter to avoid hiding transactions with messages
  src/qt/transactionrecord.cpp
Labels: bug, gui

#1876 net: Fix stalled blockchain progression
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/test/util_tests.cpp
  src/util/time.cpp
  src/util/time.h
Labels: bug

#1735 wallet: Implement backup file management functionality
  src/backup.cpp
  src/backup.h
  src/rpcclient.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/wallet/rpcwallet.cpp
Labels: enhancement

#1877 refactor: Implement std::atomic_bool OutOfSyncByAge
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/researcher.cpp
  src/rpcblockchain.cpp
  src/scraper/scraper.cpp
  src/scraper/scraper.h
  src/scraper_net.cpp
Labels: enhancement

#1880 net: Optimize locator construction for "getblocks" messages
  src/net.cpp
Labels: enhancement

#1881 superblock: Fix regression for superblock builder optimization
  src/neuralnet/superblock.cpp
Labels: bug

#1884 rpc: Display local IP addresses in "getnetworkinfo" output
  src/net.cpp
  src/net.h
  src/rpcnet.cpp
Labels: enhancement

#1883 refactor: Combine GetOrphanRoot() and WantedByOrphan() functions
  src/main.cpp
  src/main.h
Labels: enhancement

#1885 refactor: Convert beacon and backup timers to scheduled jobs
  src/backup.cpp
  src/backup.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.h
Labels: enhancement

#1888 scheduler: Fix crash after waking from sleep
  src/scheduler.cpp
Labels: bug

#1892 refactor: Clean up remaining legacy timer code
  src/Makefile.am
  src/global_objects.hpp
  src/global_objects_noui.hpp
  src/gridcoin/researcher.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/main.cpp
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/overviewpage.cpp
  src/scraper/scraper.h
  src/test/gridcoin_tests.cpp
  src/txdb-leveldb.cpp
  src/wallet/wallet.cpp
Labels: deprecation

#1902 Add --without-brotli option to curl.mk
  depends/packages/curl.mk
Labels: build System, compatibility

#1903 test: Remove fs_tests_₿_🏃 file after the fs test
  src/test/fs_tests.cpp
Labels: bug

#1901 util, gui: Fix shutdown segfault and repair broken overview page staking status
  src/gridcoin/gridcoin.cpp
  src/gridcoin/gridcoin.h
  src/init.cpp
  src/net.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
Labels: bug, gui

#1904 scraper: Fix order of destruction for global scraper objects
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/qt/bitcoingui.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
Labels: bug

#1905 scraper: Fix global object destruction order for macOS
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
Labels: bug, compatibility

#1878 refactor: port chainparams
  src/Makefile.am
  src/alert.cpp
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/checkpoints.cpp
  src/consensus/consensus.h
  src/consensus/params.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/tally.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/protocol.h
  src/qt/bitcoin.cpp
  src/rpcblockchain.cpp
  src/rpcmining.cpp
  src/test/checkpoints_tests.cpp
  src/test/gridcoin_tests.cpp
  src/test/test_gridcoin.cpp
  src/util.cpp
  src/util.h
Labels: compatibility

#1895 script: Setup Improvements
  share/pixmaps/GrcInstallBanner.jpg
  share/pixmaps/addressbook16.bmp
  share/pixmaps/addressbook16mask.bmp
  share/pixmaps/addressbook20.bmp
  share/pixmaps/addressbook20mask.bmp
  share/pixmaps/check.ico
  share/pixmaps/favicon.ico
  share/pixmaps/gradient75.png
  share/pixmaps/gradientmiddle.png
  share/pixmaps/grc-small.png
  share/pixmaps/grc.png
  share/pixmaps/grclogo.png
  share/pixmaps/grcsimple - Copy.png
  share/pixmaps/grcsm.png
  share/pixmaps/gridcoin horizontal green.png
  share/pixmaps/gridcoin horizontal.jpg
  share/pixmaps/gridcoin horizontal.png
  share/pixmaps/gridcoin-bc.ico
  share/pixmaps/gridcoin.ico
  share/pixmaps/gridcoin.png
  share/pixmaps/gridcoin128.png
  share/pixmaps/gridcoin16.ico
  share/pixmaps/gridcoin256.png
  share/pixmaps/gridcoin32.ico
  share/pixmaps/gridcoin32.png
  share/pixmaps/gridcoin64.ico
  share/pixmaps/nsis-header.bmp
  share/pixmaps/nsis-wizard.bmp
  share/pixmaps/nsis-wizard.png
  share/pixmaps/send16.bmp
  share/pixmaps/send16mask.bmp
  share/pixmaps/send16masknoshadow.bmp
  share/pixmaps/send20.bmp
  share/pixmaps/send20mask.bmp
  share/pixmaps/splash.jpg
  share/pixmaps/splash.png
  share/setup.nsi.in
Labels: build System, enhancement
