Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-08, with the labels that each got.

#1808 contract: Standardize contract validation and add block context
  src/alert.cpp
  src/main.cpp
  src/miner.cpp
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/claim.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/contract/handler.h
  src/neuralnet/contract/message.cpp
  src/neuralnet/project.cpp
  src/neuralnet/project.h
  src/test/neuralnet/project_tests.cpp
  src/test/neuralnet/researcher_tests.cpp
Labels: mandatory

#1814 test: Remove testnet condition for standard transactions
  src/main.cpp
Labels: bug

#1810 gui: Remove useless "Detach databases at shutdown"
  src/qt/forms/optionsdialog.ui
Labels: deprecation, gui

#1815 contract: Optimize contract replay after chain reorganization
  src/main.cpp
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/handler.h
  src/neuralnet/project.cpp
  src/neuralnet/project.h
Labels: enhancement

#1809 voting: Overhaul the voting system
  src/Makefile.am
  src/appcache.cpp
  src/appcache.h
  src/contract/polls.cpp
  src/contract/polls.h
  src/contract/rpccontract.cpp
  src/kernel.cpp
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/message.cpp
  src/neuralnet/contract/message.h
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/neuralnet/superblock.cpp
  src/neuralnet/superblock.h
  src/neuralnet/voting/builders.cpp
  src/neuralnet/voting/builders.h
  src/neuralnet/voting/claims.cpp
  src/neuralnet/voting/claims.h
  src/neuralnet/voting/fwd.h
  src/neuralnet/voting/payloads.h
  src/neuralnet/voting/poll.cpp
  src/neuralnet/voting/poll.h
  src/neuralnet/voting/registry.cpp
  src/neuralnet/voting/registry.h
  src/neuralnet/voting/result.cpp
  src/neuralnet/voting/result.h
  src/neuralnet/voting/vote.cpp
  src/neuralnet/voting/vote.h
  src/qt/bitcoingui.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/overviewpage.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/votingdialog.cpp
  src/qt/votingdialog.h
  src/rpcblockchain.cpp
  src/rpcclient.cpp
  src/rpcdataacq.cpp
  src/rpcmining.cpp
  src/rpcrawtransaction.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/rpcvoting.cpp
  src/test/appcache_tests.cpp
  src/test/gridcoin_tests.cpp
  src/test/neuralnet/superblock_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: enhancement, mandatory

#1816 Reimplement transaction messages as contracts
  src/Makefile.am
  src/main.cpp
  src/main.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/tx_message.h
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsentry.cpp
  src/qt/sendcoinsentry.h
  src/qt/transactiondesc.cpp
  src/qt/walletmodel.cpp
  src/rpcblockchain.cpp
  src/rpcrawtransaction.cpp
  src/util.cpp
  src/util.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: enhancement, mandatory

#1817 staking: Sign claim contracts with coinstake transaction
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/claim.cpp
  src/neuralnet/claim.h
  src/neuralnet/voting/builders.cpp
  src/test/neuralnet/claim_tests.cpp
  src/wallet/wallet.cpp
Labels: enhancement, mandatory

#1812 add seed.gridcoin.pl to myConfig
  src/init.cpp
Labels: deprecation, enhancement

#1818 gui: Fix translations for port numbers
  src/qt/locale/bitcoin_af_ZA.ts
  src/qt/locale/bitcoin_ca_ES.ts
  src/qt/locale/bitcoin_cs.ts
  src/qt/locale/bitcoin_da.ts
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_fi.ts
  src/qt/locale/bitcoin_fr_CA.ts
  src/qt/locale/bitcoin_ja.ts
  src/qt/locale/bitcoin_nl.ts
  src/qt/locale/bitcoin_ro_RO.ts
  src/qt/locale/bitcoin_sk.ts
  src/qt/locale/bitcoin_sl_SI.ts
  src/qt/locale/bitcoin_sv.ts
  src/qt/locale/bitcoin_tr.ts
  src/qt/locale/bitcoin_zh_CN.ts
Labels: bug

#1819 gui: Add pool/investor pages to researcher wizard
  gridcoinresearch.pro
  src/Makefile.qt.include
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/qt/bitcoin.qrc
  src/qt/forms/researcherwizard.ui
  src/qt/forms/researcherwizardinvestorpage.ui
  src/qt/forms/researcherwizardmodedetailpage.ui
  src/qt/forms/researcherwizardmodepage.ui
  src/qt/forms/researcherwizardpoolpage.ui
  src/qt/forms/researcherwizardpoolsummarypage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/res/icons/round_gray_x.svg
  src/qt/res/icons/round_green_check.svg
  src/qt/res/images/ic_investor_active.svg
  src/qt/res/images/ic_investor_inactive.svg
  src/qt/res/images/ic_pool_active.svg
  src/qt/res/images/ic_pool_inactive.svg
  src/qt/res/images/ic_solo_active.svg
  src/qt/res/images/ic_solo_inactive.svg
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizard.cpp
  src/qt/researcher/researcherwizard.h
  src/qt/researcher/researcherwizardinvestorpage.cpp
  src/qt/researcher/researcherwizardinvestorpage.h
  src/qt/researcher/researcherwizardmodedetailpage.cpp
  src/qt/researcher/researcherwizardmodedetailpage.h
  src/qt/researcher/researcherwizardmodepage.cpp
  src/qt/researcher/researcherwizardmodepage.h
  src/qt/researcher/researcherwizardpoolpage.cpp
  src/qt/researcher/researcherwizardpoolpage.h
  src/qt/researcher/researcherwizardpoolsummarypage.cpp
  src/qt/researcher/researcherwizardpoolsummarypage.h
  src/qt/researcher/researcherwizardprojectspage.cpp
  src/qt/researcher/researcherwizardsummarypage.cpp
  src/qt/researcher/researcherwizardsummarypage.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/test/neuralnet/researcher_tests.cpp
Labels: enhancement, gui

#1821 util: Create parent directory
  src/util.cpp
Labels: bug

#1820 gui: Change research wizard text
  src/qt/forms/researcherwizardinvestorpage.ui
  src/qt/forms/researcherwizardpoolpage.ui
  src/qt/researcher/researcherwizard.cpp
  src/qt/researcher/researcherwizard.h
Labels: enhancement, gui

#1813 gui: Implement sidestake send display
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
  src/qt/res/icons/tx_por_ss_sent.svg
  src/qt/res/icons/tx_pos.svg
  src/qt/res/icons/tx_pos_ss.svg
  src/qt/res/icons/tx_pos_ss_sent.svg
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/rpcclient.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug, enhancement, gui

#1824 net: Update protocol version and clean up net messaging
  src/main.cpp
  src/net.cpp
  src/protocol.h
  src/version.h
Labels: mandatory

#1825 rpc, wallet: Corrections to GetAmounts
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: bug

#1828 mining: Fix coinstake/claim signature order
  src/miner.cpp
Labels: bug, mandatory

#1829 Implement TransactionRecord::Message
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/res/icons/message.svg
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/wallet/rpcwallet.cpp
Labels: bug, enhancement

#1830 gui: Tweak some minor researcher wizard details
  src/qt/bitcoingui.cpp
  src/qt/forms/researcherwizardpoolsummarypage.ui
  src/qt/forms/researcherwizardprojectspage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: bug, enhancement, gui

#1831 voting: Remove double increment in loop
  src/neuralnet/voting/poll.cpp
Labels: bug

#1832 neuralnet, scraper: Fix compilation with gcc5 and older libcurl
  src/neuralnet/beacon.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/scraper/http.cpp
Labels: bug, compatibility

#1836 Change GetEstimatedStakingFrequency text
  src/qt/bitcoingui.cpp
Labels: enhancement, gui

#1833 rpc: Add private_key_available to beaconstatus
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/rpcblockchain.cpp
Labels: enhancement

#1840 gui: Validate email address in researcher wizard
  src/qt/researcher/researcherwizardemailpage.cpp
  src/qt/researcher/researcherwizardemailpage.h
Labels: enhancement

#1841 wallet: Fix smallest coin selection for contracts
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug

#1842 rpc: Add "getrawwallettransaction" RPC function
  src/rpcserver.cpp
  src/rpcserver.h
  src/wallet/rpcwallet.cpp
Labels: enhancement

#1849 gui: Add indentation to diagnostic status bar labels
  src/qt/forms/diagnosticsdialog.ui
Labels: bug, gui

#1850 voting, gui: Fix formatting and alignment of vote shares and percent
  src/qt/votingdialog.cpp
  src/qt/votingdialog.h
Labels: bug, gui

#1851 scraper: Optimization of manifest and parts sharing between ConvergedScraperStatsCache, mapManifest, and mapParts
  src/main.cpp
  src/neuralnet/quorum.cpp
  src/scraper/fwd.h
  src/scraper/scraper.cpp
  src/scraper_net.cpp
  src/scraper_net.h
  src/test/neuralnet/superblock_tests.cpp
Labels: bug, enhancement

#1853 Clear any accrual snapshots when syncing from pre-v11
  src/neuralnet/tally.cpp
Labels: bug

#1852 wallet, rpc: Fix for self-transactions in listtransactions
  src/qt/transactionrecord.cpp
  src/wallet/wallet.cpp
Labels: bug

#1854 Remove transitional testnet code
  src/main.h
  src/miner.cpp
  src/neuralnet/voting/builders.cpp
  src/wallet/wallet.cpp
Labels: mandatory

#1855 consensus: Update Checkpoints
  src/checkpoints.cpp
Labels: mandatory

#1856 docs: Update docs to build off master
  doc/build-macos.md
  doc/build-unix.md
  doc/build-windows.md
Labels: documentation

#1857 accrual: Fix reset of accrual directory if starting sync below research age height.
  src/neuralnet/tally.cpp
Labels: bug
