Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-10, with the labels that each got.

#1899 gui: Diagnostics refresh
  src/gridcoin/researcher.cpp
  src/gridcoin/researcher.h
  src/qt/bitcoingui.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/diagnosticsdialog.h
  src/qt/forms/diagnosticsdialog.ui
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/test/data/client_state.xml
  src/test/gridcoin/researcher_tests.cpp
Labels: enhancement, gui

#1906 superblock: Optimize superblock size calculation
  src/gridcoin/superblock.h
Labels: enhancement

#1908 gui: Update default font to Inter-Regular and console font to Inconsolata
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/bitcoingui.cpp
  src/qt/res/fonts/Inconsolata-Regular.ttf
  src/qt/res/fonts/Inter-Regular.ttf
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/res/stylesheets/native_stylesheet.qss
  src/qt/rpcconsole.cpp
Labels: bug, enhancement, gui

#1911 Adjust stylesheets and scale icons to improve HiDPI side toolbar dispay
  src/qt/bitcoingui.cpp
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/res/stylesheets/native_stylesheet.qss
Labels: enhancement, gui

#1912 gui: Add "review beacon verification" button to wizard summary page
  src/gridcoin/researcher.cpp
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/researcher/researcherwizard.cpp
  src/qt/researcher/researcherwizard.h
  src/qt/researcher/researcherwizardsummarypage.cpp
  src/qt/researcher/researcherwizardsummarypage.h
Labels: bug, enhancement

#1909 rpc, wallet: Implement liststakes
  src/rpcclient.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/wallet/rpcwallet.cpp
Labels: enhancement

#1913 rpc: Add "getlaststake" RPC function
  src/gridcoin/staking/status.h
  src/main.cpp
  src/miner.cpp
  src/miner.h
  src/rpcmining.cpp
  src/rpcserver.cpp
  src/rpcserver.h
Labels: enhancement

#1914 gui: Install bold variant of Inter font
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/bitcoingui.cpp
  src/qt/res/fonts/Inter-Bold.ttf
  src/qt/res/fonts/Inter-Regular.ttf
Labels: enhancement, gui

#1917 doc: Tell user to disable win32 application support in WSL
  doc/build-windows.md
Labels: build System, documentation

#1918 rpc: Revise and expand help for beaconconvergence rpc call
  src/rpcblockchain.cpp
Labels: bug, enhancement

#1920 scheduler: Increase default update check interval to 5 days
  src/gridcoin/gridcoin.cpp
  src/init.cpp
Labels: enhancement

#1921 util: Decouple out-of-sync state from block acceptance
  src/gridcoin/quorum.cpp
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper.h
  src/gridcoin/scraper/scraper_net.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/diagnosticsdialog.cpp
  src/rpcblockchain.cpp
  src/wallet/wallet.cpp
Labels: bug

#1922 gui: Prevent multiple update dialogs from being open at the same time
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
Labels: bug, gui

#1924 doc: Fix link in build-openbsd.md
  doc/build-openbsd.md
Labels: bug, documentation

#1925 rpc: Add out-of-sync status to "getinfo" and "getblockchaininfo"
  src/rpcblockchain.cpp
  src/wallet/rpcwallet.cpp
Labels: enhancement

#1919 consensus: Add checkpoint post block v11 transition
  src/chainparams.cpp
Labels: enhancement

#1932 Modify depends packages for openSUSE and other Redhat like distributions and fix mingw bdb53 compile
  depends/packages/bdb.mk
  depends/packages/bdb53.mk
  depends/packages/boost.mk
  depends/packages/bzip2.mk
  depends/packages/curl.mk
  depends/packages/libzip.mk
  depends/packages/native_ccache.mk
  depends/packages/openssl.mk
  depends/packages/packages.mk
  depends/packages/qrencode.mk
  depends/packages/zlib.mk
Labels: bug, build System

#1934 contract: Fix ability to reorganize contracts
  src/main.cpp
Labels: bug

#1935 researcher: Add -forcecpid configuration option
  src/gridcoin/researcher.cpp
  src/init.cpp
Labels: enhancement

#1936 voting: Decrease poll duration to 90 days
  src/gridcoin/voting/builders.cpp
Labels: enhancement

#1933 refactor: Clean up transitional code for block version 11
  src/gridcoin/beacon.cpp
  src/gridcoin/claim.cpp
  src/gridcoin/claim.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/gridcoin/contract/message.cpp
  src/gridcoin/gridcoin.cpp
  src/gridcoin/project.h
  src/gridcoin/quorum.cpp
  src/gridcoin/quorum.h
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/superblock.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/payloads.h
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/poll.h
  src/gridcoin/voting/vote.cpp
  src/gridcoin/voting/vote.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/net.cpp
  src/qt/forms/researcherwizardbeaconpage.ui
  src/qt/guiutil.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/rpcblockchain.cpp
  src/rpcrawtransaction.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/rpcvoting.cpp
  src/test/gridcoin/claim_tests.cpp
  src/test/gridcoin/contract_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/version.h
  src/wallet/wallet.cpp
Labels: deprecation

#1931 accrual: Fix snapshot accrual for new CPIDs
  src/chainparams.h
  src/gridcoin/tally.cpp
  src/gridcoin/tally.h
  src/main.cpp
Labels: bug, mandatory

#1938 rpc: Clean up getblockstats
  src/rpcdataacq.cpp
Labels: bug

#1939 gui: Adds detection if version is below last mandatory
  src/gridcoin/upgrade.cpp
Labels: enhancement, gui

#1940 scraper, rpc: Correct missing mScraperStats initialization in ConvergedScraperStats
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/superblock.h
Labels: bug

#1941 refactor: Revert init order to fix rejected net messages
  src/gridcoin/gridcoin.cpp
  src/gridcoin/gridcoin.h
  src/init.cpp
  src/net.cpp
Labels: bug

#1937 refactor: port amount.h
  src/Makefile.am
  src/amount.h
  src/gridcoin/account.h
  src/gridcoin/accrual/computer.h
  src/gridcoin/accrual/newbie.h
  src/gridcoin/accrual/null.h
  src/gridcoin/accrual/research_age.h
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/beacon.h
  src/gridcoin/claim.cpp
  src/gridcoin/claim.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/gridcoin/contract/message.cpp
  src/gridcoin/contract/payload.h
  src/gridcoin/project.h
  src/gridcoin/researcher.cpp
  src/gridcoin/researcher.h
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/kernel.h
  src/gridcoin/staking/reward.cpp
  src/gridcoin/staking/reward.h
  src/gridcoin/tally.cpp
  src/gridcoin/tally.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/claims.h
  src/gridcoin/voting/fwd.h
  src/gridcoin/voting/payloads.h
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/result.cpp
  src/gridcoin/voting/vote.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/rpcserver.cpp
  src/util.cpp
  src/util.h
  src/wallet/wallet.h
Labels: compatibility, refactor

#1942 refactor: Normalize boost::filesystem to fs namespace
  src/gridcoin/backup.cpp
  src/gridcoin/backup.h
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper.h
  src/gridcoin/upgrade.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/logging.cpp
  src/main.cpp
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/guiutil.cpp
  src/qt/upgradeqt.cpp
  src/rpcclient.cpp
  src/rpcdataacq.cpp
  src/rpcmining.cpp
  src/rpcprotocol.cpp
  src/rpcrawtransaction.cpp
  src/rpcserver.cpp
  src/test/gridcoin/researcher_tests.cpp
  src/test/script_tests.cpp
  src/txdb-leveldb.cpp
  src/util.h
  src/wallet/rpcdump.cpp
  src/wallet/walletdb.cpp
Labels: compatibility, refactor

#1943 contract: Reimplement legacy administrative contract validation
  src/gridcoin/contract/contract.cpp
Labels: compatibility

#1944 accrual: Apply accrual for new CPIDs from existing snapshots
  src/chainparams.h
  src/gridcoin/accrual/snapshot.h
  src/main.cpp
Labels: bug, mandatory
