Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-06, with the labels that each got.

#1696 Add verifiedbeaconreport and pendingbeaconreport
  src/rpcblockchain.cpp
  src/rpcserver.cpp
  src/rpcserver.h
  src/scraper/scraper.cpp
  src/scraper/scraper.h
Labels: enhancement

#1702 Suppress deprecated copy warnings for Qt with GCC 9+
  configure.ac
Labels: Build System

#1700 More tweaks for block version 11
  src/main.cpp
  src/neuralnet/claim.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/tally.cpp
Labels: bug

#1699 Finish the conversion to the BCLog class based logger
  src/addrman.cpp
  src/addrman.h
  src/alert.cpp
  src/banman.cpp
  src/contract/polls.cpp
  src/db.cpp
  src/init.cpp
  src/kernel.cpp
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/netbase.cpp
  src/neuralnet/quorum.cpp
  src/qt/qtipcserver.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/rpcblockchain.cpp
  src/rpcrawtransaction.cpp
  src/rpcserver.cpp
  src/scraper/http.cpp
  src/scraper/scraper.cpp
  src/scraper_net.cpp
  src/test/DoS_tests.cpp
  src/util.cpp
  src/util.h
  src/wallet.cpp
Labels: enhancement

#1701 Remove unused NetworkTimer() function and global state
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/wallet.cpp
  src/wallet.h
Labels: Deprecation

#1704 Refactor claim context objects into contracts
  src/contract/polls.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/accrual/snapshot.h
  src/neuralnet/claim.cpp
  src/neuralnet/claim.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/message.cpp
  src/neuralnet/contract/payload.h
  src/neuralnet/quorum.cpp
  src/neuralnet/quorum.h
  src/neuralnet/superblock.cpp
  src/neuralnet/superblock.h
  src/neuralnet/tally.cpp
  src/qt/bitcoingui.cpp
  src/qt/clientmodel.cpp
  src/rpcblockchain.cpp
  src/rpcmining.cpp
  src/rpcrawtransaction.cpp
  src/test/neuralnet/claim_tests.cpp
  src/test/neuralnet/contract_tests.cpp
Labels: enhancement, mandatory

#1706 Add preliminary testing option for block v11 height on testnet
  src/init.cpp
  src/main.h
Labels: temporary

#1710 Fix exclusion error on stats processing and misplaced ENDLOCK logging entry
  src/neuralnet/quorum.cpp
  src/scraper/scraper.cpp
Labels: bug

#1711 Add verified beacons manifest part to superblock validator
  src/neuralnet/quorum.cpp
  src/scraper/scraper.cpp
Labels: bug

#1712 Move claim version transitional code in miner for proper signature
  src/miner.cpp
Labels: bug

#1707 Fixed typo
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/neuralnet/tally.h
  src/qt/bitcoin.cpp
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
  src/upgrade.cpp
Labels: bug

#1713 Fix out-of-bounds exception for peers tab version slashes
  src/qt/peertablemodel.cpp
  src/qt/rpcconsole.cpp
Labels: bug

#1714 Fix transition for v1 superblocks when reorganizing
  src/neuralnet/quorum.cpp
Labels: bug

#1715 Touch up transition to version 2 transactions
  src/main.cpp
  src/main.h
  src/txdb-leveldb.cpp
  src/wallet.cpp
Labels: bug

#1716 Avoid mutating transactions in ConnectBlock()
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/accrual/snapshot.h
  src/neuralnet/beacon.cpp
  src/neuralnet/claim.cpp
  src/neuralnet/claim.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/project.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/superblock.cpp
  src/neuralnet/superblock.h
  src/rpcblockchain.cpp
  src/rpcdataacq.cpp
  src/rpcmining.cpp
  src/rpcrawtransaction.cpp
  src/test/neuralnet/claim_tests.cpp
  src/wallet.cpp
Labels: bug, mandatory

#1718 Clean old assets up
  doc/assets-attribution.md
  src/Makefile.qt.include
  src/qt/res/icons/2tx_cpumined.png
  src/qt/res/icons/bitcoin_testnet.ico
  src/qt/res/icons/gold_cpumined.gif
  src/qt/res/icons/mine.png
  src/qt/res/icons/overview2.png
  src/qt/res/icons/rsz_chat.png
  src/qt/res/icons/statistics.png
  src/qt/res/icons/toolbar.png
  src/qt/res/icons/toolbar_testnet.png
  src/qt/res/icons/tx2.png
  src/qt/res/icons/tx_minedoie_WOEI3ooIzGHI.png
  src/qt/res/icons/wwww.png
  src/qt/res/images/grcoverview.png
  src/qt/res/images/r1.qrc
Labels: Deprecation

#1717 Implement beacon, vote, and superblock display categories/icons in UI transaction model
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/res/icons/superblock.svg
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/wallet.cpp
  src/wallet.h
Labels: enhancement, mandatory

#1726 Skip beacon advertisement when already pending
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/rpcblockchain.cpp
Labels: bug, mandatory

#1728 Fix Windows cross-compilation in newer environments
  configure.ac
  depends/packages/bzip2.mk
  depends/patches/bzip2/Makefile.patch
  src/util/time.cpp
Labels: bug, compatibility

#1730 doc: Update threads in coding.txt
  doc/coding.txt
Labels: documentation

#1733 qt: Include QPainterPath in trafficgraphwidget.cpp
  src/qt/trafficgraphwidget.cpp
Labels: compatibility

#1731 doc: Update doc/build-unix.md
  doc/build-unix.md
Labels: build System

#1734 gui: Show peers tab on connections icon click
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: enhancement

#1722 refactor: Change return type of IsMine to isminetype && move wallet files to wallet directory
  src/Makefile.am
  src/backup.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/init.h
  src/main.cpp
  src/main.h
  src/miner.h
  src/net.cpp
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/message.cpp
  src/qt/addresstablemodel.cpp
  src/qt/addresstablemodel.h
  src/qt/bitcoingui.cpp
  src/qt/coincontroldialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiondesc.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpcclient.cpp
  src/rpcnet.cpp
  src/rpcprotocol.cpp
  src/rpcrawtransaction.cpp
  src/rpcserver.cpp
  src/scraper/scraper.h
  src/script.cpp
  src/script.h
  src/test/DoS_tests.cpp
  src/test/accounting_tests.cpp
  src/test/base64_tests.cpp
  src/test/multisig_tests.cpp
  src/test/neuralnet/contract_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_tests.cpp
  src/test/test_gridcoin.cpp
  src/test/transaction_tests.cpp
  src/test/util_tests.cpp
  src/test/wallet_tests.cpp
  src/wallet/coincontrol.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/ismine.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: bug, enhancement

#1736 Fix out-of-bounds access in IsMineInner()
  src/script.cpp
Labels: bug

#1727 neuralnet: Add integrity checking to researcher accrual snapshot registry
  src/Makefile.am
  src/filehash.h
  src/neuralnet/accrual/snapshot.h
  src/neuralnet/tally.cpp
Labels: enhancement, mandatory

#1738 Fix a couple of block version 11 issues
  src/miner.cpp
  src/neuralnet/beacon.cpp
Labels: bug, mandatory

#1673 build: Updates boost to 1.73.0 for depends
  configure.ac
  depends/packages/boost.mk
Labels: build System, compatibility

#1739 gui: Build onboarding/beacon wizard
  gridcoinresearch.pro
  src/Makefile.qt.include
  src/contract/polls.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/net.cpp
  src/neuralnet/accrual/snapshot.h
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/quorum.h
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/neuralnet/tally.cpp
  src/neuralnet/tally.h
  src/qt/bitcoin.cpp
  src/qt/bitcoin.qrc
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/bitcoinstrings.cpp
  src/qt/forms/overviewpage.ui
  src/qt/forms/researcherwizard.ui
  src/qt/forms/researcherwizardauthpage.ui
  src/qt/forms/researcherwizardbeaconpage.ui
  src/qt/forms/researcherwizardemailpage.ui
  src/qt/forms/researcherwizardprojectspage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/res/icons/warning.svg
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/res/stylesheets/native_stylesheet.qss
  src/qt/researcher/projecttablemodel.cpp
  src/qt/researcher/projecttablemodel.h
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizard.cpp
  src/qt/researcher/researcherwizard.h
  src/qt/researcher/researcherwizardauthpage.cpp
  src/qt/researcher/researcherwizardauthpage.h
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/qt/researcher/researcherwizardbeaconpage.h
  src/qt/researcher/researcherwizardemailpage.cpp
  src/qt/researcher/researcherwizardemailpage.h
  src/qt/researcher/researcherwizardprojectspage.cpp
  src/qt/researcher/researcherwizardprojectspage.h
  src/qt/researcher/researcherwizardsummarypage.cpp
  src/qt/researcher/researcherwizardsummarypage.h
  src/rpcblockchain.cpp
  src/rpcclient.cpp
  src/scraper/scraper.cpp
  src/scraper/scraper.h
  src/test/neuralnet/beacon_tests.cpp
  src/test/neuralnet/researcher_tests.cpp
  src/ui_interface.h
Labels: enhancement

#1741 Fix null pointer dereference in GUI researcher model
  src/qt/researcher/researchermodel.cpp
Labels: bug

#1742 Remove legacy "rain" RPC (not by-project rain)
  src/Makefile.am
  src/contract/rain.cpp
  src/contract/rain.h
  src/rpcblockchain.cpp
  src/rpcserver.cpp
  src/rpcserver.h
Labels: deprecation

#1723 doc: Add CONTRIBUTING.md from bitcoin/bitcoin
  CONTRIBUTING.md
Labels: documentation

#1744 rpc: Implement inspectaccrualsnapshot and parseaccrualsnapshotfile
  src/neuralnet/accrual/snapshot.h
  src/rpcblockchain.cpp
  src/rpcclient.cpp
  src/rpcmining.cpp
  src/rpcserver.cpp
  src/rpcserver.h
Labels: enhancement, rpc

#1745 Reset research accounts when rebuilding accrual snapshots
  src/neuralnet/tally.cpp
Labels: bug, mandatory

#1747 scraper: Correct update for verified beacons
  src/scraper/fwd.h
  src/scraper/scraper.cpp
Labels: bug, mandatory

#1749 Refactor tally initialization for snapshot rebuild
  src/neuralnet/accrual/snapshot.h
  src/neuralnet/tally.cpp
Labels: bug, mandatory

#1750 Fix "cpid" field in "beaconconvergence" RPC output
  src/rpcblockchain.cpp
Labels: bug

#1751 scraper: Add disk based state backing for verified beacon list in scraper
  src/scraper/fwd.h
  src/scraper/scraper.cpp
Labels: bug, mandatory

#1752 accrual: Fix snapshot accrual superblock state transitions
  src/neuralnet/quorum.cpp
  src/neuralnet/tally.cpp
  src/rpcmining.cpp
  src/rpcserver.cpp
  src/rpcserver.h
Labels: bug, mandatory

#1753 scraper: Correct stale verified beacon logic
  src/scraper/scraper.cpp
Labels: bug, mandatory

#1754 scraper: Shorten display representation of verification codes
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/superblock.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizardauthpage.cpp
  src/rpcblockchain.cpp
  src/scraper/fwd.h
  src/scraper/scraper.cpp
  src/test/neuralnet/beacon_tests.cpp
  src/test/neuralnet/superblock_tests.cpp
Labels: compatibility, enhancement, mandatory

#1755 rpc: Correct possible divide by zero in getblockstats
  src/rpcdataacq.cpp
Labels: bug

#1756 gui: Fix issues with researcher wizard flow
  src/neuralnet/researcher.cpp
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/rpcblockchain.cpp
Labels: bug, enhancement

#1737 util: Fix braindamage in GetDefaultDataDir()
  src/init.cpp
  src/logging.cpp
  src/qt/guiutil.cpp
  src/scraper/scraper.cpp
  src/util.cpp
Labels: bug

#1760 scraper: Improve scraper processing of beacon verifications
  src/scraper/scraper.cpp
Labels: enhancement, mandatory

#1761 Don't count empty email as explicit investor
  src/neuralnet/researcher.cpp
Labels: bug

#1764 accrual: Fix snapshot accrual superblock state transitions
  src/main.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/superblock.cpp
  src/neuralnet/superblock.h
  src/neuralnet/tally.cpp
  src/rpcmining.cpp
Labels: bug, mandatory

#1763 scraper: Add instrumentation to convergencereport
  src/rpcblockchain.cpp
  src/rpcclient.cpp
  src/scraper/scraper.cpp
Labels: enhancement

#1767 rpc: Improve rpc stress test script
  contrib/rpcstresstest/rpc_stress_test.sh
Labels: enhancement
