Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-11, with the labels that each got.

#1947 accrual: Reset research account when disconnecting first block
  src/chainparams.h
  src/gridcoin/account.h
  src/gridcoin/tally.cpp
Labels: bug

#1948 voting: Add poll choices to "gettransaction" RPC contract output
  src/rpcrawtransaction.cpp
Labels: enhancement

#1945 refactor: [Memory optimization] Remove duplicate PoS state from the block index
  src/Makefile.am
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/kernel.h
  src/gridcoin/staking/spam.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/txdb-leveldb.cpp
Labels: enhancement

#1951 gui: Add RAC column to wizard summary page projects table
  src/qt/researcher/projecttablemodel.cpp
  src/qt/researcher/projecttablemodel.h
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: enhancement, gui

#1950 refactor: [Memory optimization] Block index superblock and contract flags
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/quorum.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/tally.cpp
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/result.cpp
  src/main.cpp
  src/main.h
  src/rpcblockchain.cpp
  src/rpcdataacq.cpp
  src/rpcmining.cpp
  src/txdb-leveldb.cpp
  src/wallet/wallet.cpp
Labels: enhancement

#1954 refactor: [Memory optimization] Remove stake modifier checksums
  src/gridcoin/gridcoin.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/kernel.h
  src/main.cpp
  src/main.h
  src/rpcblockchain.cpp
  src/txdb-leveldb.cpp
Labels: enhancement

#1957 refactor: [Memory optimization] Block index allocation overhead
  src/Makefile.am
  src/gridcoin/account.h
  src/gridcoin/block_index.h
  src/gridcoin/tally.cpp
  src/main.cpp
  src/main.h
  src/rpcblockchain.cpp
  src/rpcdataacq.cpp
  src/rpcmining.cpp
  src/rpcrawtransaction.cpp
  src/txdb-leveldb.cpp
  src/wallet/wallet.cpp
Labels: enhancement

#1960 refactor: [Memory optimization] Remove block index subsidy fields
  src/main.cpp
  src/main.h
  src/rpcblockchain.cpp
  src/rpcdataacq.cpp
  src/rpcrawtransaction.cpp
  src/txdb-leveldb.cpp
Labels: enhancement

#1961 refactor: [Memory optimization] Separate chain trust from the block index
  src/Makefile.am
  src/gridcoin/staking/chain_trust.h
  src/main.cpp
  src/main.h
  src/rpcblockchain.cpp
  src/txdb-leveldb.cpp
  src/txdb-leveldb.h
Labels: enhancement

#1962 refactor: [Memory optimization] Eliminate padding between block index fields
  src/main.cpp
  src/main.h
Labels: enhancement

#1959 gui: fix mandatory/leisure detection of upgrade check
  src/gridcoin/upgrade.cpp
Labels: bug

#1963 researcher: Remove automatic legacy beacon key import
  src/gridcoin/gridcoin.cpp
  src/gridcoin/researcher.cpp
  src/gridcoin/researcher.h
  src/wallet/wallet.cpp
Labels: deprecation

#1966 rpc: clean up the superblocks function and add magnitude to getmininginfo
  src/rpcblockchain.cpp
  src/rpcmining.cpp
Labels: enhancement

#1969 Revert "Close LevelDB after loading the block index"
  src/main.cpp
Labels: bug

#1968 beacon, gui: Add check for presence of beacon private key to updateBeacon()
  src/gridcoin/beacon.cpp
  src/qt/researcher/researchermodel.cpp
Labels: bug

#1970 voting: Fix title in "gettransaction" RPC for legacy poll contracts
  src/gridcoin/contract/contract.cpp
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/poll.h
Labels: bug

#1971 rpc: Add transaction size to RPC output
  src/rpcrawtransaction.cpp
Labels: enhancement

#1972 gui: Fix missing menu items on macOS
  src/qt/bitcoingui.cpp
Labels: bug, compatibility

#1974 rpc: Fix answer offset in "votedetails"
  src/rpcvoting.cpp
Labels: bug

#1973 util: Enhance ETTS calculation
  src/gridcoin/staking/difficulty.cpp
  src/util.h
Labels: enhancement

#1964 ci: migrate to github actions
  .github/workflows/ci.yml
  .travis.yml
  ci/lint/04_install.sh
  ci/lint/06_script.sh
  ci/test/00_setup_env_mac.sh
  ci/test/03_before_install.sh
  ci/test/04_install.sh
  ci/test/05_before_script.sh
  ci/test/06_script_b.sh
  ci/test/wrap-qemu.sh
  ci/test/wrap-wine.sh
  ci/test_run_all.sh
Labels: build System, deprecation, enhancement

#1975 refactor: Use new clamp in util.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/quorum.cpp
  src/gridcoin/staking/reward.cpp
  src/miner.cpp
  src/test/gridcoin/superblock_tests.cpp
Labels: refactor

#1976 voting: Add user-facing support for poll response types
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/poll.h
  src/gridcoin/voting/result.cpp
  src/qt/votingdialog.cpp
  src/qt/votingdialog.h
  src/rpcclient.cpp
  src/rpcvoting.cpp
Labels: enhancement
