Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-07, with the labels that each got.

#1768 Add ability to recover beacon in block version 11+
  src/main.cpp
  src/neuralnet/beacon.cpp
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/neuralnet/tally.cpp
  src/qt/forms/researcherwizardbeaconpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/rpcblockchain.cpp
  src/rpcclient.cpp
  src/test/neuralnet/beacon_tests.cpp
Labels: enhancement, mandatory

#1769 Temporarily disable voting system on testnet
  src/contract/polls.cpp
Labels: temporary

#1770 Generalize enum serialization
  src/Makefile.am
  src/Makefile.test.include
  src/enumbytes.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/contract/payload.h
  src/test/enumbytes.cpp
  src/test/neuralnet/contract_tests.cpp
Labels: enhancement

#1772 gui: Remove legacy GUI transaction description for contracts
  src/qt/transactiondesc.cpp
  src/rpcrawtransaction.cpp
Labels: temporary

#1773 Fix scraper etag header case sensitivity
  src/scraper/http.cpp
  src/scraper/scraper.cpp
Labels: bug

#1774 consensus: Use explicit time to check if superblock needed
  src/main.cpp
  src/miner.cpp
  src/neuralnet/quorum.cpp
  src/neuralnet/quorum.h
  src/neuralnet/superblock.h
  src/rpcblockchain.cpp
  src/scraper/scraper.cpp
Labels: enhancement, mandatory

#1776 scraper: Improve handling of ETags in http class and tweak verified beacon logic
  src/scraper/http.cpp
  src/scraper/scraper.cpp
Labels: bug

#1778 scraper: Improve ProcessNetworkWideFromProjectStats and other tweaks
  src/scraper/scraper.cpp
  src/scraper_net.cpp
Labels: bug, enhancement, mandatory

#1777 refactor: Add transaction context to contract handlers
  src/main.cpp
  src/main.h
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/contract/handler.h
  src/neuralnet/contract/message.cpp
  src/neuralnet/project.cpp
  src/neuralnet/project.h
  src/test/neuralnet/contract_tests.cpp
  src/test/neuralnet/project_tests.cpp
  src/test/neuralnet/researcher_tests.cpp
Labels: enhancement, mandatory

#1780 gui: Remove transaction fee setting
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/sendcoinsdialog.cpp
Labels: bug, gui

#1781 researcher: Automate beacon advertisement for renewals only
  src/main.cpp
Labels: enhancement

#1775 gui: Add context for when BOINC is attached to a pool
  src/neuralnet/researcher.cpp
  src/neuralnet/researcher.h
  src/test/neuralnet/researcher_tests.cpp
Labels: enhancement

#1784 gui: Tweak behavior of beacon page in researcher wizard
  src/qt/forms/researcherwizardauthpage.ui
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researcherwizardbeaconpage.cpp
Labels: bug, gui

#1785 Fix GUI scroll area dark theme styles
  src/qt/forms/researcherwizardauthpage.ui
  src/qt/res/stylesheets/dark_stylesheet.qss
Labels: bug, gui

#1787 Prepare for block version 11 hard-fork on testnet
  src/main.cpp
  src/main.h
  src/neuralnet/contract/payload.h
  src/test/neuralnet/contract_tests.cpp
Labels: mandatory

#1791 scraper: Modify UpdateVerifiedBeaconsFromConsensus
  src/scraper/scraper.cpp
Labels: bug

#1789 rpc: gui: Fix three divide by zero possibilities
  src/qt/upgradeqt.cpp
  src/qt/votingdialog.cpp
  src/rpcmining.cpp
  src/upgrade.cpp
  src/upgrade.h
Labels: bug

#1792 rpc: Fix balance pre-check in "rainbymagnitude" RPC
  src/rpcblockchain.cpp
Labels: bug

#1793 trivial: Cleanup unused legacy functions
  src/contract/polls.cpp
  src/contract/polls.h
  src/main.cpp
  src/main.h
  src/test/util_tests.cpp
  src/util/time.cpp
  src/util/time.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: deprecation

#1796 mining, rpc: Remove kernel-diff-best and kernel-diff-sum
  src/miner.cpp
  src/rpcmining.cpp
  src/wallet/wallet.h
Labels: deprecation

#1799 consensus: Switch snapshot accrual calculation to integer arithmetic
  src/neuralnet/accrual/snapshot.h
Labels: bug, mandatory

#1794 gui: Optimize OverviewPage::updateTransactions()
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: enhancement, gui

#1795 ci: Adopt ci changes from bitcoin
  .travis.yml
  build-aux/m4/bitcoin_qt.m4
  ci/README.md
  ci/retry/README.md
  ci/retry/retry
  ci/test/00_setup_env.sh
  ci/test/00_setup_env_arm.sh
  ci/test/00_setup_env_linux_i386.sh
  ci/test/00_setup_env_mac.sh
  ci/test/00_setup_env_mac_host.sh
  ci/test/00_setup_env_native.sh
  ci/test/00_setup_env_win32.sh
  ci/test/00_setup_env_win64.sh
  ci/test/03_before_install.sh
  ci/test/04_install.sh
  ci/test/05_before_script.sh
  ci/test/06_script_a.sh
  ci/test/06_script_b.sh
  ci/test_run_all.sh
  depends/builders/darwin.mk
  depends/hosts/darwin.mk
  depends/hosts/default.mk
  depends/packages/boost.mk
  depends/packages/curl.mk
  depends/packages/native_biplist.mk
  depends/packages/native_cctools.mk
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
  depends/packages/qt59.mk
  depends/patches/qt59/fix_configure_mac.patch
  depends/patches/qt59/mac-qmake.conf
  src/test/neuralnet/cpid_tests.cpp
  src/test/neuralnet/superblock_tests.cpp
  src/test/util_tests.cpp
Labels: build System, compatibility

#1803 scraper: cleanup unused/unnecessary functions
  src/rpcblockchain.cpp
  src/scraper/scraper.cpp
  src/scraper/scraper.h
Labels: deprecation

#1802 refactor: Remove libs subdirectory
  libs/.gitignore
Labels: deprecation

#1801 gui: Fix stuck cursor on labels
  src/qt/forms/aboutdialog.ui
  src/qt/forms/overviewpage.ui
  src/qt/forms/researcherwizardauthpage.ui
  src/qt/forms/researcherwizardprojectspage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/forms/rpcconsole.ui
  src/qt/forms/sendcoinsdialog.ui
Labels: bug, gui

#1805 beacon: Fix researcher wizard beacon renewal status
  src/qt/researcher/researchermodel.cpp
Labels: bug

#1804 qt: Add option to choose not to start the wallet minimized
  src/qt/bitcoin.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: bug, enhancement, gui

#1806 superblock: Add check for OutOfSyncByAge to SuperblockValidator::Validate
  src/neuralnet/quorum.cpp
Labels: bug, mandatory
