Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-12, with the labels that each got.

#1980 Implement missing try-catch in VotingVoteDialog::vote
  src/qt/votingdialog.cpp
Labels: bug

#1978 gui: Port Bitcoin Intro class (implement the ability to choose a data directory via the GUI)
  src/Makefile.qt.include
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/forms/intro.ui
  src/qt/forms/overviewpage.ui
  src/qt/guiconstants.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/intro.cpp
  src/qt/intro.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/util.cpp
  src/util.h
Labels: bug, enhancement, gui

#1977 scraper: Add check for minimum housekeeping complete in scraper
  src/gridcoin/quorum.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper.h
  src/gridcoin/superblock.h
  src/rpcblockchain.cpp
Labels: bug

#1983 gui: Redo global status for overview
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/difficulty.h
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/bitcoingui.cpp
  src/qt/clientmodel.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiconstants.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/util/time.cpp
  src/util/time.h
  src/wallet/wallet.cpp
Labels: bug, enhancement, gui

#1988 voting: Fix nonsense vote weights for legacy polls
  src/gridcoin/voting/result.cpp
Labels: bug

#1989 voting: Fix incorrect field returned in ResolveMoneySupplyForPoll()
  src/gridcoin/voting/result.cpp
Labels: bug

#1990 ci: Fix python symlink issue & remove travis
  .github/workflows/ci.yml
  .travis.yml
Labels: build System, compatibility, deprecation

#1987 util: Improvements to MilliTimer class and use in the miner and init
  src/gridcoin/staking/status.h
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/miner.cpp
  src/qt/bitcoin.cpp
  src/rpcmining.cpp
  src/util/time.cpp
  src/util/time.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: enhancement

#1991 gui: Port Bitcoin MacOS app nap manager
  share/qt/Info.plist.in
  src/Makefile.qt.include
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/macos_appnap.h
  src/qt/macos_appnap.mm
Labels: compatibility, enhancement

#1992 mining, rpc: Implement staking efficiency measure and improve SelectCoinsForStaking and CreateCoinStake
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/kernel.h
  src/gridcoin/staking/status.h
  src/miner.cpp
  src/rpcmining.cpp
  src/util/time.cpp
  src/util/time.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: enhancement
