Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2020-05, with the labels that each got.

#1669 Overhaul the contract handling system
  src/Makefile.am
  src/Makefile.test.include
  src/appcache.cpp
  src/appcache.h
  src/beacon.cpp
  src/contract/contract.cpp
  src/contract/contract.h
  src/contract/cpid.cpp
  src/contract/cpid.h
  src/contract/message.cpp
  src/contract/message.h
  src/contract/polls.cpp
  src/contract/rain.cpp
  src/contract/rain.h
  src/contract/rpccontract.cpp
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/neuralnet/beacon.cpp
  src/neuralnet/beacon.h
  src/neuralnet/claim.cpp
  src/neuralnet/contract.cpp
  src/neuralnet/contract.h
  src/neuralnet/project.cpp
  src/neuralnet/project.h
  src/qt/bitcoingui.cpp
  src/rpcblockchain.cpp
  src/rpcrawtransaction.cpp
  src/scraper/scraper.cpp
  src/test/beacon_tests.cpp
  src/test/neuralnet/contract_tests.cpp
  src/test/neuralnet/project_tests.cpp
  src/test/wallet_tests.cpp
  src/wallet.cpp
  src/wallet.h
Labels: enhancement

#1671 Make the autostart mainnet/testnet aware
  src/qt/guiutil.cpp
Labels: bug, enhancement

#1677 Fix suffix when copying txids
  src/qt/transactionrecord.cpp
Labels: bug

#1693 replaced deprecated QT methods
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/peertablemodel.cpp
  src/qt/transactiontablemodel.cpp
Labels: compatibility

#1697 Touch up some details for block version 11
  src/main.cpp
  src/main.h
  src/neuralnet/quorum.cpp
  src/rpcblockchain.cpp
Labels: mandatory

#1698 Add support for type-specific contract fee amounts
  src/main.cpp
  src/neuralnet/beacon.h
  src/neuralnet/contract/contract.cpp
  src/neuralnet/contract/contract.h
  src/neuralnet/contract/message.cpp
  src/neuralnet/contract/payload.h
  src/neuralnet/project.h
  src/test/neuralnet/beacon_tests.cpp
  src/test/neuralnet/contract_tests.cpp
  src/test/neuralnet/project_tests.cpp
Labels: enhancement, mandatory
