Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-10, with the labels that each got.

#2350 test: Repair transaction_tests.cpp (baseline)
  src/init.cpp
  src/test/data/tx_valid.json
  src/test/data/tx_valid.json.disabled
  src/test/script_tests.cpp
  src/test/test_gridcoin.cpp
  src/test/transaction_tests.cpp
  src/util.cpp
  src/util.h
Labels: bug, build system, compatibility

#2354 build: pin OpenSSL version for MacOS
  .github/workflows/ci.yml
  configure.ac
  doc/build-macos.md
Labels: build system, compatibility

#2355 refactor: port upstream ui_interface changes
  src/Makefile.am
  src/alert.cpp
  src/banman.cpp
  src/dbwrapper.cpp
  src/gridcoin/gridcoin.cpp
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/staking/status.cpp
  src/gridcoin/upgrade.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/registry.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/main.cpp
  src/net.cpp
  src/node/ui_interface.cpp
  src/node/ui_interface.h
  src/noui.cpp
  src/qt/bitcoin.cpp
  src/qt/clientmodel.cpp
  src/qt/optionsmodel.cpp
  src/qt/qtipcserver.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/upgradeqt.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/walletmodel.cpp
  src/rpc/client.cpp
  src/rpc/protocol.cpp
  src/rpc/server.cpp
  src/ui_interface.h
  src/util.cpp
  src/wallet/db.cpp
  src/wallet/rpcdump.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: compatibility, refactor

#2358 scraper: Fix scraper deadlock and make activebeforesb dynamic (not require restart)
  src/gridcoin/scraper/scraper.cpp
Labels: bug

#2363 test: Update util_tests from upstream
  src/test/util_tests.cpp
Labels: build system, compatibility

#2367 refactor: split clientversion from version
  .gitattributes
  Makefile.am
  src/Makefile.am
  src/addrdb.cpp
  src/alert.cpp
  src/clientversion.cpp
  src/clientversion.h
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/gridcoinresearchd-res.rc
  src/init.cpp
  src/node/blockstorage.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/forms/rpcconsole.ui
  src/qt/res/gridcoinresearch.rc
  src/qt/rpcconsole.cpp
  src/util.cpp
  src/util/macros.h
  src/version.cpp
  src/version.h
  src/wallet/db.h
  src/wallet/rpcdump.cpp
  test/lint/lint-includes.sh
Labels: compatibility

#2370 scraper: Move lock on cs_mapParts in RecvManifest
  src/gridcoin/scraper/scraper_net.cpp
Labels: bug

#2371 build: Make changes to use Gridcoin x.y.z.w client versions
  share/genbuild.sh
  src/clientversion.cpp
  src/clientversion.h
Labels: bug, compatibility

#2365 refactor, build: Upstream fixes for the /crypto files. Implement Keccak and SHA3
  configure.ac
  src/Makefile.am
  src/compat/cpuid.h
  src/crypto/chacha20.cpp
  src/crypto/chacha20.h
  src/crypto/common.h
  src/crypto/ripemd160.cpp
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha256.h
  src/crypto/sha3.cpp
  src/crypto/sha3.h
  src/crypto/sha512.cpp
  src/crypto/siphash.cpp
  src/crypto/siphash.h
Labels: enhancement, compatibility

#2368 random: port upstream random changes
  contrib/devtools/test_deterministic_coverage.sh
  src/Makefile.am
  src/Makefile.test.include
  src/addrdb.cpp
  src/addrman.cpp
  src/addrman.h
  src/crypto/sha512.h
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/spam.h
  src/init.cpp
  src/main.cpp
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/qt/winshutdownmonitor.cpp
  src/random.cpp
  src/random.h
  src/randomenv.cpp
  src/randomenv.h
  src/rpc/server.cpp
  src/scheduler.cpp
  src/script.cpp
  src/test/dos_tests.cpp
  src/test/merkle_tests.cpp
  src/test/mruset_tests.cpp
  src/test/random_tests.cpp
  src/test/scheduler_tests.cpp
  src/test/test_gridcoin.cpp
  src/test/util_tests.cpp
  src/util.cpp
  src/util.h
  src/wallet/wallet.cpp
Labels: enhancement, compatibility
