Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-05, with the labels that each got.

#2119 util, rpc, gui: Implement GetMaxInputsForConsolidationTxn()
  src/chainparams.h
  src/miner.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/qt/coincontroldialog.cpp
  src/rpc/rawtransaction.cpp
Labels: enhancement

#2122 depends: change boost mirror
  depends/packages/boost.mk
Labels: build System, deprecation

#2123 refactor: small cleanup
  contrib/devtools/circular-dependencies.py
  contrib/devtools/copyright_header.py
  src/addrdb.cpp
  src/main.cpp
  src/main.h
  src/net.h
  src/protocol.cpp
  src/protocol.h
Labels: refactor

#2129 build: Update depends Qt recipe to version 5.12.10
  .github/workflows/ci.yml
  build-aux/m4/bitcoin_qt.m4
  ci/test_run_all.sh
  depends/hosts/darwin.mk
  depends/packages/dbus.mk
  depends/packages/libX11.mk
  depends/packages/libXext.mk
  depends/packages/libxkbcommon.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/xextproto.mk
  depends/packages/xtrans.mk
  depends/patches/qt/drop_lrelease_dependency.patch
  depends/patches/qt/fix_android_jni_static.patch
  depends/patches/qt/fix_android_pch.patch
  depends/patches/qt/fix_android_qmake_conf.patch
  depends/patches/qt/fix_bigsur_drawing.patch
  depends/patches/qt/fix_configure_mac.patch
  depends/patches/qt/fix_lib_paths.patch
  depends/patches/qt/fix_mingw_cross_compile.patch
  depends/patches/qt/fix_no_printer.patch
  depends/patches/qt/fix_powerpc_libpng.patch
  depends/patches/qt/fix_qpainter_non_determinism.patch
  depends/patches/qt/fix_qt_pkgconfig.patch
  depends/patches/qt/fix_rcc_determinism.patch
  depends/patches/qt/fix_riscv64_arch.patch
  depends/patches/qt/freetype_back_compat.patch
  depends/patches/qt/no-xlib.patch
  depends/patches/qt/no_sdk_version_check.patch
  depends/patches/qt/qtbase-moc-ignore-gcc-macro.patch
  depends/patches/qt/xkb-default.patch
Labels: build System, compatibility

#2125 gui: Implement consolidateunspent wizard
  src/Makefile.qt.include
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/consolidateunspentdialog.h
  src/qt/consolidateunspentwizard.cpp
  src/qt/consolidateunspentwizard.h
  src/qt/consolidateunspentwizardselectdestinationpage.cpp
  src/qt/consolidateunspentwizardselectdestinationpage.h
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/qt/consolidateunspentwizardselectinputspage.h
  src/qt/consolidateunspentwizardsendpage.cpp
  src/qt/consolidateunspentwizardsendpage.h
  src/qt/forms/consolidateunspentwizard.ui
  src/qt/forms/consolidateunspentwizardselectdestinationpage.ui
  src/qt/forms/consolidateunspentwizardselectinputspage.ui
  src/qt/forms/consolidateunspentwizardsendpage.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
Labels: enhancement, gui

#2134 Remove CCT from README, add Discord
  README.md
Labels: deprecation, documentation

#2135 Bump Codespell to 2.0.0
  ci/lint/04_install.sh
Labels: build System

#2131 scraper, util, qt: Fix several deprecations and warnings
  src/gridcoin/scraper/scraper_net.h
  src/net.h
  src/qt/bitcoin.cpp
  src/qt/guiutil.cpp
  src/qt/optionsmodel.cpp
  src/qt/rpcconsole.cpp
Labels: bug

#2139 gui: Fix duplicate time in GUIUtil::dateTimeStr()
  src/qt/guiutil.cpp
Labels: bug, gui

#2137 gui: Optimize locks to improve responsiveness
  src/Makefile.am
  src/qt/bitcoingui.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/wallet/generated_type.h
  src/wallet/wallet.h
Labels: enhancement, gui

#2138 gui: Refresh "receive payment" page design
  gridcoinresearch.pro
  src/Makefile.qt.include
  src/qt/addressbookpage.cpp
  src/qt/addressbookpage.h
  src/qt/bitcoin.qrc
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/addressbookpage.ui
  src/qt/forms/receivecoinspage.ui
  src/qt/receivecoinspage.cpp
  src/qt/receivecoinspage.h
  src/qt/res/icons/icons_dark/search.svg
  src/qt/res/icons/icons_light/search.svg
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: enhancement, gui

#2140 gui: Add empty placeholder to recent transactions list
  gridcoinresearch.pro
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/forms/noresult.ui
  src/qt/forms/overviewpage.ui
  src/qt/noresult.cpp
  src/qt/noresult.h
  src/qt/overviewpage.cpp
  src/qt/res/icons/no_result.svg
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: enhancement, gui

#2142 gui: Fix debug console traffic graph legend colors
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: bug, gui

#2104 gui: Fix nomenclature
  src/gridcoin/researcher.cpp
  src/qt/forms/rpcconsole.ui
  src/qt/rpcconsole.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/votingdialog.cpp
  src/qt/votingdialog.h
Labels: documentation, gui

#2145 gui: Refresh address book page design
  gridcoinresearch.pro
  src/Makefile.qt.include
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/favoritespage.cpp
  src/qt/favoritespage.h
  src/qt/forms/favoritespage.ui
  src/qt/transactionview.cpp
Labels: enhancement, gui

#2148 doc: Update http to https where possible
  CHANGELOG.md
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  contrib/devtools/clang-format-diff.py
  contrib/macdeploy/LICENSE
  doc/Doxyfile.in
  doc/README.md
  doc/assets-attribution.md
  doc/build-macos.md
  doc/gitian-building.md
  doc/readme-qt.rst
  src/crypto/ctaes/README.md
  src/crypto/ctaes/ctaes.c
  src/leveldb/doc/benchmark.html
  src/leveldb/doc/impl.md
  src/leveldb/port/atomic_pointer.h
  src/leveldb/port/port_posix.h
  src/leveldb/util/env_win.cc
  src/qt/notificator.cpp
  src/rpc/protocol.cpp
  src/threadsafety.h
  src/tinyformat.h
  src/util.cpp
  src/wallet/rpcdump.cpp
Labels: documentation

#2149 doc: Fix Typos
  CHANGELOG.md
  depends/packages.md
  src/gridcoin/beacon.h
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/upgrade.cpp
  src/leveldb/port/atomic_pointer.h
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/qt/decoration.h
  src/qt/macnotificationhandler.mm
  src/qt/notificator.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
Labels: documentation

#2150 Qt: Add antialiasing to traffic graph widget
  src/qt/trafficgraphwidget.cpp
Labels: enhancement, gui
