Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-12, with the labels that each got.

#2399 gui: Implement privacy mode
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/bitcoinunits.cpp
  src/qt/bitcoinunits.h
  src/qt/noresult.cpp
  src/qt/noresult.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: enhancement, gui

#2403 gui: Fix bug in recent transaction list
  src/qt/overviewpage.cpp
Labels: bug

#2401 build: Drop macports support
  configure.ac
  doc/readme-qt.rst
Labels: build system, documentation, deprecation

#2400 util: Check if specified config file cannot be opened
  src/util/system.cpp
Labels: bug, compatibility

#2394 util: Implement -reindex option, improve -loadblock option
  src/gridcoin/upgrade.cpp
  src/gridcoin/upgrade.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/qt/bitcoingui.cpp
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
Labels: enhancement, compatibility

#2406 gui: Implement Alt-7 for unlock and lock of wallet
  src/qt/bitcoingui.cpp
Labels: enhancement

#2396 contract: separate legacy type parsing
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/test/gridcoin/contract_tests.cpp
Labels: refactor

#2409 net: Remove I2P support from netbase & Correct HE IPv6 Tunnel Broker
  src/netbase.cpp
  src/netbase.h
Labels: bug, compatibility

#2408 refactor: Pass values by reference
  src/net.cpp
  src/netbase.cpp
  src/netbase.h
Labels: enhancement, compatibility

#2411 net: only adjust time with data from outbound nodes
  src/main.cpp
Labels: enhancement, compatibility

#2410 qt: Remove locked coins loop
  src/qt/walletmodel.cpp
Labels: deprecation

#2412 net: Fix masking of irrelevant bits in address groups
  src/netbase.cpp
  src/test/netbase_tests.cpp
Labels: bug, compatibility

#2413 rpc: Change call to FormatISO8601DateTime to FormatISO8601DateTimeDashSep in scanforunspent
  src/rpc/rawtransaction.cpp
Labels: bug

#2415 rpc: accept int block number for getblocksbatch
  src/rpc/blockchain.cpp
Labels: bug, rpc

#2416 gui, voting: Add a one minute timer to check for current poll expiring and update gui
  src/gridcoin/voting/registry.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
Labels: bug, gui

#2260 build: Adjust depends packages to successfully compile on OpenSUSE
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/freetype.mk
  depends/packages/libXau.mk
  depends/packages/libxcb.mk
  depends/packages/libxkbcommon.mk
  depends/packages/xcb_proto.mk
  depends/packages/xproto.mk
  depends/patches/bzip2/Makefile.patch
Labels: build system, compatibility

#2414 gui: Implement a warning about split CPID/email mismatch condition
  src/gridcoin/researcher.cpp
  src/gridcoin/researcher.h
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizardsummarypage.cpp
Labels: enhancement, gui
