Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-07, with the labels that each got.

#2207 build: macOS toolchain bump
  ci/test/00_setup_env_mac.sh
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/macdeploy/README.md
  depends/hosts/darwin.mk
  depends/packages/native_cctools.mk
  depends/packages/native_clang.mk
  depends/packages/native_libtapi.mk
  depends/packages/packages.mk
Labels: build system, compatibility

#2212 Update build-unix.md
  doc/build-unix.md
Labels: build system, documentation

#2210 voting, rpc, gui: Implement demand loading of historical poll by poll id and AVW calculation
  src/gridcoin/researcher.cpp
  src/gridcoin/researcher.h
  src/gridcoin/superblock.cpp
  src/gridcoin/superblock.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/registry.h
  src/qt/forms/voting/pollcard.ui
  src/qt/voting/pollcard.cpp
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/voting.cpp
Labels: enhancement, gui, rpc

#2219 build: Bump minimum python version to 3.6, Remove python2 references
  configure.ac
Labels: build system, compatibility

#2218 gui: Show GUI error dialog if command line parsing fails
  src/qt/bitcoin.cpp
Labels: enhancement, gui

#2216 gui: Implement close confirmation.
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: enhancement, gui

#2233 util: Tweak exception handling in MilliTimer class to eliminate compiler warnings
  src/util/time.cpp
Labels: bug

#2237 depends: Change openSSL source path to Github
  depends/packages/openssl.mk
Labels: build system

#2234 depends: patch missing include in qt
  depends/packages/qt.mk
  depends/patches/qt/fix_limits_header.patch
Labels: bug, build system

#2232 build: Use -fstack-reuse=none
  configure.ac
Labels: bug, build system

#2242 wallet, rpc: Check each input for IsMine() in GetAddressGroupings
  src/wallet/wallet.cpp
Labels: bug

#2243 doc: Fix typo in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#2244 ci: fold depends output
  ci/test/05_before_script.sh
Labels: build system

#2246 util, qt: Fix snapshot download
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/http.h
  src/gridcoin/upgrade.cpp
  src/gridcoin/upgrade.h
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
Labels: bug, compatibility

#2241 GUI: Fix Column Widths in RPC Console. Elide long strings in their center. Indent user agent.
  src/qt/forms/rpcconsole.ui
  src/qt/rpcconsole.h
Labels: enhancement, gui

#2248 rpc: Remove readconfig
  src/rpc/blockchain.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: deprecation

#2250 qt: Fix crash during download snapshot on macOS
  src/gridcoin/scraper/http.cpp
  src/gridcoin/upgrade.cpp
  src/qt/bitcoingui.cpp
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
Labels: bug, gui

#2245 Qt: Don't allow to open the debug window during splashscreen & verification state
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
Labels: bug, gui
