Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-09, with the labels that each got.

#2310 rpc: Don't use floating point in getreceivedbyaddress
  src/wallet/rpcwallet.cpp
Labels: bug, compatibility

#2313 rpc: ParseHash: Fail when length is not 64
  src/rpc/server.cpp
Labels: bug, compatibility

#2314 Fix locking on WSL using flock instead of fcntl
  src/fs.cpp
Labels: bug, compatibility

#2308 refactor, qt: Drop redundant setEditTriggers(NoEditTriggers) calls, Fix typo in QtInputSupport check
  build-aux/m4/bitcoin_qt.m4
  src/qt/rpcconsole.cpp
Labels: bug, compatibility

#2307 rpc: Fix breakage in protocol.cpp caused by change from atoi to ParseInt
  src/rpc/protocol.cpp
Labels: bug

#2293 release: Remove gitian
  ci/test/00_setup_env_mac.sh
  ci/test/00_setup_env_win32.sh
  ci/test/00_setup_env_win64.sh
  contrib/devtools/README.md
  contrib/devtools/symbol-check.py
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
  contrib/macdeploy/README.md
  doc/README.md
  doc/gitian-building.md
  doc/gitian-building/all_files_in_one_partition.png
  doc/gitian-building/create_new_vm.png
  doc/gitian-building/create_vm_file_location_size.png
  doc/gitian-building/create_vm_hard_disk.png
  doc/gitian-building/create_vm_hard_disk_file_type.png
  doc/gitian-building/create_vm_memsize.png
  doc/gitian-building/create_vm_storage_physical_hard_disk.png
  doc/gitian-building/debian_install_10_configure_clock.png
  doc/gitian-building/debian_install_11_partition_disks.png
  doc/gitian-building/debian_install_12_choose_disk.png
  doc/gitian-building/debian_install_14_finish.png
  doc/gitian-building/debian_install_15_write_changes.png
  doc/gitian-building/debian_install_16_choose_a_mirror.png
  doc/gitian-building/debian_install_18_proxy_settings.png
  doc/gitian-building/debian_install_19_software_selection.png
  doc/gitian-building/debian_install_1_boot_menu.png
  doc/gitian-building/debian_install_20_install_grub.png
  doc/gitian-building/debian_install_21_install_grub_bootloader.png
  doc/gitian-building/debian_install_22_finish_installation.png
  doc/gitian-building/debian_install_2_select_a_language.png
  doc/gitian-building/debian_install_3_select_location.png
  doc/gitian-building/debian_install_4_configure_keyboard.png
  doc/gitian-building/debian_install_5_configure_the_network.png
  doc/gitian-building/debian_install_6_domain_name.png
  doc/gitian-building/debian_install_6a_set_up_root_password.png
  doc/gitian-building/debian_install_7_set_up_user_fullname.png
  doc/gitian-building/debian_install_8_set_up_username.png
  doc/gitian-building/debian_install_9_user_password.png
  doc/gitian-building/debian_root_login.png
  doc/gitian-building/network_settings.png
  doc/gitian-building/port_forwarding_rules.png
  doc/gitian-building/select_startup_disk.png
  doc/release-process.md
  test/lint/lint-shell.sh
Labels: build system, deprecation

#2320 net: Small upstream FIXME
  src/net.cpp
  src/rpc/net.cpp
Labels: enhancement

#2292 refactor: Fix advanced compiler warnings
  configure.ac
  src/consensus/tx_verify.cpp
  src/crypter.cpp
  src/crypter.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/gridcoin.h
  src/gridcoin/magnitude.h
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/superblock.h
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/keystore.cpp
  src/keystore.h
  src/main.cpp
  src/miner.cpp
  src/net.cpp
  src/policy/fees.h
  src/prevector.h
  src/qt/addresstablemodel.cpp
  src/qt/bitcoin.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/walletmodel.cpp
  src/rpc/client.cpp
  src/rpc/protocol.cpp
  src/rpc/server.cpp
  src/rpc/voting.cpp
  src/script.h
  src/sync.cpp
  src/sync.h
  src/test/accounting_tests.cpp
  src/test/gridcoin/beacon_tests.cpp
  src/test/gridcoin/cpid_tests.cpp
  src/test/gridcoin/magnitude_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/test/multisig_tests.cpp
  src/test/script_p2sh_tests.cpp
  src/test/sigopcount_tests.cpp
  src/test/wallet_tests.cpp
  src/util.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: compatibility, refactor

#2317 build: update m4
  build-aux/m4/ax_boost_base.m4
  build-aux/m4/ax_boost_chrono.m4
  build-aux/m4/ax_boost_filesystem.m4
  build-aux/m4/ax_boost_iostreams.m4
  build-aux/m4/ax_boost_system.m4
  build-aux/m4/ax_boost_thread.m4
  build-aux/m4/ax_boost_unit_test_framework.m4
  build-aux/m4/ax_check_compile_flag.m4
  build-aux/m4/ax_check_link_flag.m4
  build-aux/m4/ax_check_preproc_flag.m4
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  build-aux/m4/ax_gcc_func_attribute.m4
  build-aux/m4/ax_pthread.m4
  depends/config.guess
  depends/config.sub
Labels: build system, compatibility

#2322 poll: Fix the possible infinite loop warning on GetChoices() in result.cpp
  src/gridcoin/voting/result.cpp
Labels: bug

#2316 qt: Replace deprecated Qt functions
  src/qt/addresstablemodel.cpp
  src/qt/bitcoinamountfield.cpp
  src/qt/researcher/researcherwizardmodedetailpage.cpp
  src/qt/voting/pollwizardtypepage.cpp
  src/qt/voting/votewizardballotpage.cpp
Labels: compatibility, deprecation

#2324 qt: fix broken research wizard signal
  src/qt/researcher/researcherwizardmodepage.cpp
Labels: bug, gui

#2318 build: set minimum required Boost to 1.60
  configure.ac
  src/qt/qtipcserver.cpp
Labels: build system, compatibility, deprecation

#2249 cd: generate release binaries using GitHub actions
  .github/workflows/cd.yml
  Makefile.am
  cd/00_setup_env.sh
  cd/00_setup_env_mac.sh
  cd/00_setup_env_win32.sh
  cd/00_setup_env_win64.sh
  cd/03_before_install.sh
  cd/04_install.sh
  cd/05_before_script.sh
  cd/06_script_a.sh
  cd/06_script_b.sh
  cd/run_all.sh
  share/setup.nsi.in
Labels: enhancement, build system

#2327 refactor: Fix three minor code scanner findings
  contrib/macdeploy/macdeployqtplus
  src/qt/walletmodel.cpp
  src/scheduler.cpp
Labels: bug, refactor

#2329 Fix build with Boost 1.77.0
  src/fs.cpp
Labels: compatibility

#2323 util: port upstream span changes
  src/span.h
Labels: enhancement

#2319 util: Don't use gmtime() or localtime()
  src/gridcoin/backup.cpp
  src/logging.cpp
  src/logging.h
  src/rpc/rawtransaction.cpp
Labels: bug, deprecation

#2330 util: Update scheduler and remove Boost chrono
  build-aux/m4/ax_boost_chrono.m4
  ci/test/00_setup_env_native.sh
  ci/test/00_setup_env_native_old.sh
  configure.ac
  depends/packages/boost.mk
  doc/build-openbsd.md
  doc/build-unix.md
  gridcoinresearch.pro
  src/Makefile.am
  src/Makefile.test.include
  src/gridcoin/backup.cpp
  src/gridcoin/gridcoin.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/logging.cpp
  src/miner.cpp
  src/net.cpp
  src/qt/bitcoin.cpp
  src/qt/qtipcserver.cpp
  src/qt/rpcconsole.cpp
  src/qt/upgradeqt.cpp
  src/rpc/server.cpp
  src/scheduler.cpp
  src/scheduler.h
  src/test/scheduler_tests.cpp
  src/threadinterrupt.cpp
  src/threadinterrupt.h
  src/util.cpp
  src/util.h
  src/util/time.cpp
  src/util/time.h
  src/wallet/db.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.cpp
Labels: enhancement, build system, compatibility, deprecation

#2332 qt: remove gridcoinresearch.pro
  gridcoinresearch.pro
Labels: build system, deprecation

#2335 build: Update univalue subtree
  src/rpc/protocol.cpp
  src/rpc/rawtransaction.cpp
  src/univalue/Makefile.am
  src/univalue/README.md
  src/univalue/gen/gen.cpp
  src/univalue/include/univalue.h
  src/univalue/lib/univalue.cpp
  src/univalue/lib/univalue_read.cpp
  src/univalue/lib/univalue_write.cpp
  src/univalue/test/fail45.json
  src/univalue/test/object.cpp
  src/univalue/test/pass4.json
  src/univalue/test/unitester.cpp
Labels: compatibility, deprecation

#2334 rpc: add additional ban time fields to listbanned
  src/rpc/net.cpp
Labels: enhancement, compatibility

#2331 build: Misc upstream depends fixes
  depends/funcs.mk
  depends/packages.md
  depends/packages/bdb.mk
  depends/packages/bdb53.mk
  depends/packages/boost.mk
  depends/packages/freetype.mk
  depends/packages/libICE.mk
  depends/packages/libSM.mk
  depends/packages/libXau.mk
  depends/packages/libevent.mk
  depends/packages/libxcb.mk
  depends/packages/miniupnpc.mk
  depends/packages/xcb_proto.mk
  depends/packages/xproto.mk
Labels: enhancement, build system, compatibility

#2315 refactor: Scraper thread safety and code cleanup
  src/gridcoin/gridcoin.cpp
  src/gridcoin/quorum.cpp
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/fwd.h
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper.h
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoin/scraper/scraper_net.h
  src/gridcoin/superblock.h
  src/main.cpp
  src/test/gridcoin/superblock_tests.cpp
Labels: enhancement, refactor

#2339 wallet: Fix improper indent in encryptWallet
  src/qt/bitcoingui.cpp
Labels: bug

#2333 qt: Follow Qt docs when implementing rowCount and columnCount
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/peertablemodel.cpp
  src/qt/researcher/projecttablemodel.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/voting/polltablemodel.cpp
Labels: enhancement

#2337 wallet: Bugfix - Fundrawtransaction: don't terminate when keypool is empty
  src/wallet/wallet.cpp
Labels: bug

#2342 depends: Fix build for Apple Silicon
  depends/packages/bdb.mk
  depends/packages/bdb53.mk
  depends/packages/openssl.mk
  depends/packages/qt.mk
Labels: build system, compatibility

#2343 test: Add sanity_tests from upstream
  src/Makefile.test.include
  src/test/sanity_tests.cpp
Labels: build system, compatibility

#2345 util, test: Don't allow Base58 decoding of non-Base58 strings. Add Base58 tests. Add whitespace tests.
  src/base58.h
  src/test/base58_tests.cpp
  src/util/strencodings.cpp
Labels: enhancement, build system, compatibility

#2340 build: fix -fstack-clash-protection spam for Clang
  configure.ac
Labels: build system, compatibility

#2344 util, test: Don't allow Base32/64-decoding or ParseMoney(…) on strings with embedded NUL characters. Add tests. Add negative test case.
  src/test/base32_tests.cpp
  src/test/base64_tests.cpp
  src/test/util_tests.cpp
  src/util.cpp
  src/util/strencodings.cpp
Labels: enhancement, build system, compatibility

#2347 test: Remove unused function dumpKeyInfo
  src/test/key_tests.cpp
Labels: deprecation

#2348 test: Add tests for monetary value formatting and parsing. Clean up includes in rpc_tests
  src/test/rpc_tests.cpp
Labels: build system, compatibility

#2349 rpc: Implement -rpcwait and -rpcwaittimeout
  src/init.cpp
  src/rpc/client.cpp
Labels: enhancement, rpc, compatibility

#2351 build: remove glibc back compat
  ci/test/00_setup_env_arm.sh
  configure.ac
  doc/build-unix.md
  src/Makefile.am
Labels: build system, compatibility, deprecation

#2352 qt: Notificator class refactoring. Notificator always takes 3 args. Remove Growl support.
  src/qt/bitcoingui.cpp
  src/qt/macnotificationhandler.h
  src/qt/macnotificationhandler.mm
  src/qt/notificator.cpp
  src/qt/notificator.h
Labels: compatibility, deprecation
