Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-11, with the labels that each got.

#2372 test: Add crypto_tests from upstream
  src/Makefile.test.include
  src/test/crypto_tests.cpp
Labels: build system, compatibility

#2373 refactor: convert C-style (void) parameter lists to C++ style ()
  src/init.cpp
  src/key.h
  src/qt/macnotificationhandler.h
  src/test/wallet_tests.cpp
Labels: compatibility

#2376 util: fix FormatVersion
  src/clientversion.cpp
  src/util.h
Labels: bug

#2377 build: Disable -fcf-protection for mingw win32
  configure.ac
Labels: bug, compatibility

#2378 gui: Add text output and dialog boxes for -help and -version in GUI client
  src/qt/bitcoin.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
Labels: bug

#2380 test: Add test for GCC bug 90348
  src/Makefile.test.include
  src/test/compilerbug_tests.cpp
Labels: build system, compatibility

#2382 depends: avoid system harfbuzz and bz2
  depends/packages/freetype.mk
Labels: build system, compatibility

#2383 doc: Update Windows build instructions
  doc/build-windows.md
Labels: build system, documentation

#2387 refactor: replace QDateTime::fromTime_t with QDateTime::fromSecsSinceEpoch
  src/qt/clientmodel.cpp
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/qt/guiutil.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactiontablemodel.cpp
Labels: compatibility, deprecation

#2386 build: add python3.10, 3.11 alias to AC_PATH_PROGS call in configure
  configure.ac
Labels: build system, compatibility

#2385 net: remove SOCKS4 support from core and GUI
  src/init.cpp
  src/netbase.cpp
  src/netbase.h
  src/qt/diagnosticsdialog.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/rpc/net.cpp
  src/wallet/rpcwallet.cpp
Labels: compatibility, deprecation

#2384 util: Port of Bitcoin upstream base58.h/cpp at a85442f62bf157b07849accd495c55c73535dc73
  src/Makefile.am
  src/base58.cpp
  src/base58.h
Labels: enhancement, compatibility

#2391 test: update base58_encode_decode.json from upstream
  src/test/data/base58_encode_decode.json
Labels: build system, compatibility

#2390 net: initialize nMessageSize to uint32_t max
  src/protocol.cpp
  src/protocol.h
Labels: build system, compatibility

#2389 depends: Port libdmg-hfsplus changes from upstream
  depends/packages/native_libdmg-hfsplus.mk
  depends/patches/native_libdmg-hfsplus/remove-libcrypto-dependency.patch
Labels: build system, compatibility

#2162 doc: Port newer build documentation from Bitcoin
  doc/build-freebsd.md
  doc/build-macos.md
  doc/build-openbsd.md
  doc/build-unix.md
Labels: build system, documentation

#2388 wallet, contract: Implement contract change option
  src/gridcoin/contract/message.cpp
  src/init.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: enhancement, gui

#2366 net: remove obsolete "reply" command
  src/addrman.h
  src/main.cpp
  src/net.cpp
  src/net.h
Labels: deprecation

#2395 contract: fix double usage of contract change addresses
  src/gridcoin/contract/message.cpp
Labels: bug

#2397 build: patch qt to explicitly define previously implicit header include
  depends/packages/qt.mk
  depends/patches/qt/fix_montery_include.patch
Labels: build system, compatibility

#2398 Fix breakage introduced by use of FormatISO8601DateTime
  src/gridcoin/backup.cpp
  src/util/time.cpp
  src/util/time.h
Labels: bug

#2393 rpc: Change getmininginfo to getstakinginfo
  src/gridcoin/staking/status.cpp
  src/miner.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/overviewpage.cpp
  src/qt/researcher/researchermodel.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: gui, compatibility
