Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-02, with the labels that each got.

#2008 beacon: Change beacon map to pointers.
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/tally.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/test/gridcoin/beacon_tests.cpp
Labels: enhancement

#2013 rpc: Add boolean option to report active beacons only in beaconreport
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
Labels: enhancement

#2016 log: grammar correction
  src/main.cpp
Labels: bug

#2014 Update bitcoin_sv.ts
  src/qt/locale/bitcoin_sv.ts
Labels: gui

#2019 util: Update snapshot URLs and add accrual directory
  src/gridcoin/scraper/http.cpp
  src/gridcoin/upgrade.cpp
Labels: bug, enhancement

#2020 beacon: Tweak BeaconRegistry::Revert
  src/gridcoin/beacon.cpp
Labels: bug

#2021 wallet: Correct nMinFee fee calculation in CreateTransaction
  src/wallet/wallet.cpp
Labels: bug

#2023 rpc, qt: bump fees
  src/qt/coincontroldialog.cpp
  src/rpc/rawtransaction.cpp
Labels: bug

#2026 rpc, miner: Correct GetLastStake
  src/miner.cpp
Labels: bug

#2022 consensus: Set Hilda mainnet hardfork height to 2197000
  src/chainparams.h
  src/version.h
Labels: mandatory

#2029 wallet: Fix bug in CreateTransaction causing insufficient fees
  src/main.cpp
  src/wallet/wallet.cpp
Labels: bug
