Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-04, with the labels that each got.

#2085 gui: Change scraper tab to Inconsolata monospace font
  src/qt/forms/rpcconsole.ui
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/res/stylesheets/native_stylesheet.qss
  src/qt/rpcconsole.cpp
Labels: enhancement, gui

#2084 consensus: Reimplement checkpoint-based spam protection
  src/chainparams.cpp
  src/chainparams.h
  src/checkpoints.cpp
  src/checkpoints.h
  src/main.cpp
  src/test/checkpoints_tests.cpp
Labels: enhancement

#2089 refactor: Remove LessVerbose() function
  src/main.cpp
  src/miner.cpp
Labels: deprecation

#2088 gui: Fix shutdown response for failed core init
  src/gridcoin/gridcoin.cpp
  src/init.cpp
  src/qt/bitcoin.cpp
Labels: bug

#2090 researcher: Fix deferment of beacon renewal in superblock window
  src/gridcoin/researcher.cpp
Labels: bug

#2092 researcher: Change beacon deferment fix to reference nActiveBeforeSB
  src/gridcoin/researcher.cpp
Labels: bug

#2091 gui: Fix typo in beacon status refresh
  src/qt/researcher/researchermodel.cpp
Labels: bug

#2078 doc: Update build doc
  doc/build-unix.md
Labels: build System, documentation

#2096 gui: Normalize button and input control appearance
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/res/icons/icons_dark/chevron_up.svg
  src/qt/res/icons/icons_light/chevron_up.svg
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: enhancement, gui

#2097 consensus: Implement GetMinimumRequiredConnectionsForStaking
  src/chainparams.h
  src/miner.cpp
Labels: enhancement

#2006 refactor: move CTransaction to primitives
  src/Makefile.am
  src/consensus/consensus.h
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/gridcoin/tx_message.cpp
  src/gridcoin/tx_message.h
  src/gridcoin/voting/registry.cpp
  src/index/disktxpos.h
  src/index/txindex.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/policy/fees.h
  src/policy/policy.cpp
  src/policy/policy.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/qt/bitcoin.cpp
  src/qt/coincontroldialog.cpp
  src/qt/transactiondesc.cpp
  src/rpc/blockchain.cpp
  src/rpc/blockchain.h
  src/rpc/rawtransaction.cpp
  src/script.cpp
  src/script.h
  src/test/multisig_tests.cpp
  src/test/script_p2sh_tests.cpp
  src/test/transaction_tests.cpp
  src/txdb-leveldb.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: compatibility, refactor

#2093 Changes for snapshotdownload and add feature sync from zero
  src/gridcoin/gridcoin.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoin/upgrade.h
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/init.h
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/diagnosticsdialog.cpp
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
Labels: enhancement, gui

#2094 consensus, refactor, test: Merkle
  src/Makefile.am
  src/Makefile.test.include
  src/chainparams.cpp
  src/consensus/merkle.cpp
  src/consensus/merkle.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/test/merkle_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: enhancement

#2095 gui: Update diagnostics
  src/qt/diagnosticsdialog.cpp
  src/qt/diagnosticsdialog.h
  src/qt/forms/diagnosticsdialog.ui
Labels: bug, enhancement

#2100 rpc: Remove obsolete comparesnapshotaccrual RPC function
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: deprecation, rpc

#2107 gui: Have the TrafficGraphWidget respect the selected stylesheet.
  src/qt/trafficgraphwidget.cpp
Labels: enhancement, gui

#2106 gui: Fix macOS display inconsistencies
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/decoration.cpp
  src/qt/decoration.h
  src/qt/diagnosticsdialog.cpp
  src/qt/forms/diagnosticsdialog.ui
  src/qt/forms/overviewpage.ui
  src/qt/forms/researcherwizardauthpage.ui
  src/qt/forms/researcherwizardemailpage.ui
  src/qt/forms/researcherwizardinvestorpage.ui
  src/qt/forms/researcherwizardmodedetailpage.ui
  src/qt/forms/researcherwizardmodepage.ui
  src/qt/forms/researcherwizardpoolpage.ui
  src/qt/forms/researcherwizardpoolsummarypage.ui
  src/qt/forms/researcherwizardsummarypage.ui
  src/qt/forms/rpcconsole.ui
  src/qt/guiconstants.h
  src/qt/overviewpage.cpp
  src/qt/res/fonts/Inter-Bold.otf
  src/qt/res/fonts/Inter-Medium.otf
  src/qt/res/fonts/Inter-Regular.otf
  src/qt/res/fonts/Inter-VariableFont.ttf
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/researcher/researcherwizardauthpage.cpp
  src/qt/researcher/researcherwizardinvestorpage.cpp
  src/qt/researcher/researcherwizardmodedetailpage.cpp
  src/qt/researcher/researcherwizardmodepage.cpp
  src/qt/researcher/researcherwizardpoolpage.cpp
  src/qt/researcher/researcherwizardpoolsummarypage.cpp
  src/qt/researcher/researcherwizardsummarypage.cpp
  src/qt/rpcconsole.cpp
Labels: bug, gui

#2108 gui: Fix RPC console auto-complete background color
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: bug, gui

#2109 gui: Avoid reloading redundant stylesheets
  src/qt/bitcoingui.cpp
Labels: enhancement, gui

#2110 gui: Fix "no active beacon" status
  src/qt/researcher/researchermodel.cpp
Labels: bug, gui

#2101 rpc: Remove deprecated RPC commands
  src/rpc/blockchain.cpp
  src/rpc/dataacq.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: deprecation

#2115 gui: Fix dark theme link text color visibility
  src/qt/bitcoingui.cpp
Labels: enhancement, gui

#2114 gui: Set standard base Qt style on Windows and macOS
  src/qt/bitcoin.cpp
Labels: bug, enhancement, gui

#2111 gui: Implement GUI version of consolidateunspent (coin control part)
  src/Makefile.qt.include
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/consolidateunspentdialog.cpp
  src/qt/consolidateunspentdialog.h
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/consolidateunspentdialog.ui
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
Labels: enhancement, gui
