Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-08, with the labels that each got.

#2253 gui: Fix address book selected model record when editing
  src/qt/addressbookpage.cpp
Labels: bug, gui

#2254 researcher: Check wallet status before beacon renewal
  src/gridcoin/researcher.cpp
Labels: bug, gui

#2255 qt: Prevent pasting (no label) as label in consolidation transaction
  src/qt/sendcoinsdialog.cpp
Labels: bug, gui

#2220 qt: Remove stray QT4 references
  doc/gridcoinresearch.1
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/test/test_main.cpp
  src/qt/winshutdownmonitor.cpp
  src/qt/winshutdownmonitor.h
Labels: deprecation

#2221 wallet: Close DB on error, use memory_cleanse
  src/base58.h
  src/util.cpp
  src/wallet/db.cpp
  src/wallet/db.h
Labels: bug

#2224 build: Clean remnants of QTBUG-34748 fix
  depends/packages/libxcb.mk
Labels: build system

#2225 build: use -isysroot over --sysroot on macOS
  contrib/macdeploy/README.md
  depends/builders/darwin.mk
  depends/hosts/darwin.mk
Labels: build system

#2226 build: libevent 2.1.12-stable
  depends/packages/libevent.mk
Labels: build system, compatibility

#2227 trivial, rpc: Fix and cleanup listreceivedbyX documentation, General Typos
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/upgrade.cpp
  src/qt/forms/voting/pollwizardprojectpage.ui
  src/rpc/rawtransaction.cpp
  src/wallet/rpcwallet.cpp
Labels: documentation

#2228 trivial: Unbreak build with Boost 1.72.0
  src/fs.h
Labels: bug, compatibility

#2231 util: Remove old boost hacks/workarounds
  configure.ac
  src/gridcoin/backup.cpp
  src/scheduler.cpp
  src/util/time.cpp
Labels: compatibility, deprecation

#2247 doc: Large collection of typos, grammar fixes, and proper capitalization
  CHANGELOG.md
  configure.ac
  contrib/gitian-build.sh
  contrib/rpcstresstest/README.md
  doc/README.md
  doc/build-unix.md
  doc/readme-qt.rst
  doc/release-process.md
  src/addrman.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/gridcoin.cpp
  src/gridcoin/scraper/http.h
  src/gridcoin/superblock.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoin/voting/registry.cpp
  src/gridcoinresearchd.cpp
  src/leveldb/db/corruption_test.cc
  src/miner.cpp
  src/net.cpp
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoinstrings.cpp
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/script.cpp
  src/sync.cpp
  src/test/README.md
  src/test/gridcoin/beacon_tests.cpp
  src/test/wallet_tests.cpp
  src/txdb-leveldb.cpp
  src/txdb-leveldb.h
  src/wallet/wallet.cpp
Labels: documentation

#2262 refactor: Replace fprintf with tfm::format
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/noui.cpp
  src/qt/bitcoin.cpp
  src/qt/guiutil.cpp
  src/qt/qtipcserver.cpp
  src/rpc/client.cpp
  src/sync.cpp
  src/txdb-leveldb.cpp
  src/util.cpp
  src/util/system.cpp
Labels: compatibility

#2261 qt: Replace deprecated QSignalMapper by lambda expressions
  src/qt/rpcconsole.cpp
Labels: deprecation, enhancement

#2265 refactor: Use functions guaranteed to be locale independent (ToLower, IsDigit, IsSpace)
  src/base58.h
  src/bignum.h
  src/gridcoin/project.cpp
  src/gridcoin/scraper/scraper.cpp
  src/rpc/protocol.cpp
  src/test/getarg_tests.cpp
  src/test/script_tests.cpp
  src/test/util_tests.cpp
  src/util.cpp
Labels: compatibility

#2266 refactor: Replace std::to_string with locale-independent alternative
  src/gridcoin/quorum.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/voting/builders.cpp
  src/rpc/blockchain.cpp
  src/rpc/dataacq.cpp
  src/rpc/rawtransaction.cpp
  src/test/gridcoin/beacon_tests.cpp
  src/wallet/wallet.cpp
Labels: compatibility

#2267 refactor: small python cleanup
  contrib/wallettools/walletchangepass.py
  contrib/wallettools/walletunlock.py
  share/qt/extract_strings_qt.py
Labels: enhancement

#2269 refactor: Remove sprintf and printf
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/upgrade.cpp
  src/test/getarg_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
Labels: enhancement

#2270 refactor: Replace local dependent string functions with non-locale versions in strencodings.h/cpp
  src/bignum.h
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/researcher.cpp
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/staking/reward.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/result.cpp
  src/gridcoin/voting/vote.cpp
  src/init.cpp
  src/miner.cpp
  src/net.cpp
  src/netbase.cpp
  src/qt/bitcoingui.cpp
  src/rpc/client.cpp
  src/rpc/dataacq.cpp
  src/rpc/protocol.cpp
  src/rpc/server.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/util.cpp
  src/util/strencodings.cpp
  src/util/strencodings.h
  src/util/system.cpp
  src/wallet/wallet.h
Labels: enhancement

#2271 ci: Update KNOWN_VIOLATIONS list for the linter for functions we don't care are locale-dependent
  test/lint/lint-locale-dependence.sh
Labels: build system

#2277 depends: Remove boost::program_options dependency
  build-aux/m4/ax_boost_program_options.m4
  ci/test/00_setup_env_native.sh
  ci/test/00_setup_env_native_old.sh
  configure.ac
  depends/packages/boost.mk
  doc/build-openbsd.md
  doc/build-unix.md
  doc/readme-qt.rst
  gridcoinresearch.pro
  src/util.cpp
Labels: deprecation

#2273 refactor: move block storage functions to src/node/blockstorage
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/quorum.cpp
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/registry.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/node/blockstorage.cpp
  src/node/blockstorage.h
  src/rpc/blockchain.cpp
  src/rpc/dataacq.cpp
  src/rpc/rawtransaction.cpp
  src/txdb-leveldb.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
Labels: enhancement, compatibility

#2278 refactor: Drop noop gcc version checks
  src/compat.h
Labels: compatibility

#2280 util: Remove unused itostr
  src/util/strencodings.cpp
  src/util/strencodings.h
  src/wallet/wallet.h
Labels: compatibility

#2275 refactor: Replace deprecated Qt::SystemLocale{Short,Long}Date, Fix 'QDateTime is deprecated' warnings
  src/qt/bantablemodel.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/transactionview.cpp
Labels: deprecation

#2236 util: Remove deprecated random number generator functions
  src/qt/winshutdownmonitor.cpp
  src/util.cpp
Labels: deprecation

#2279 depends: cleanup package configure flags
  depends/packages/libXau.mk
  depends/packages/libxcb.mk
  depends/packages/qrencode.mk
  depends/packages/xproto.mk
Labels: build system, compatibility

#2276 lint: Fix linter warning, fix typo
  share/qt/extract_strings_qt.py
  src/qt/sendcoinsdialog.cpp
  test/lint/lint-shell.sh
Labels: enhancement, documentation

#2284 build: add stack-clash and control-flow protection options to hardening flags, don't enable it for Windows
  configure.ac
Labels: enhancement, build system

#2282 rpc: remove 'label' filter for rpc command help
  src/rpc/server.cpp
Labels: deprecation

#2283 wallet : remove unused fNoncriticalErrors variable from CWalletDB::FindWalletTx
  src/wallet/walletdb.cpp
Labels: deprecation

#2288 build: add upstream compiler warnings
  Makefile.am
  configure.ac
  src/Makefile.am
  src/Makefile.leveldb.include
  src/crypto/sha256_avx2.cpp
  src/crypto/sha256_shani.cpp
  src/crypto/sha256_sse41.cpp
Labels: build system, compatibility

#2289 rpc: optimize getblockbynumber
  src/rpc/blockchain.cpp
Labels: enhancement, rpc

#2281 gui: Update connect statements to conform to Qt 5 standard
  src/qt/addressbookpage.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/bitcoinamountfield.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/clicklabel.h
  src/qt/clientmodel.cpp
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentdialog.cpp
  src/qt/consolidateunspentwizard.cpp
  src/qt/consolidateunspentwizardselectdestinationpage.cpp
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/favoritespage.cpp
  src/qt/optionsdialog.cpp
  src/qt/overviewpage.cpp
  src/qt/qrcodedialog.cpp
  src/qt/qvalidatedlineedit.cpp
  src/qt/qvaluecombobox.cpp
  src/qt/receivecoinspage.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researcherwizard.cpp
  src/qt/researcher/researcherwizardauthpage.cpp
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/qt/researcher/researcherwizardmodedetailpage.cpp
  src/qt/researcher/researcherwizardmodepage.cpp
  src/qt/researcher/researcherwizardpoolpage.cpp
  src/qt/researcher/researcherwizardpoolsummarypage.cpp
  src/qt/researcher/researcherwizardprojectspage.cpp
  src/qt/researcher/researcherwizardsummarypage.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsentry.cpp
  src/qt/trafficgraphwidget.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/transactionview.cpp
  src/qt/transactionview.h
  src/qt/walletmodel.cpp
Labels: gui, compatibility

#2295 qt: Do not translate file extensions
  src/qt/addressbookpage.cpp
  src/qt/qrcodedialog.cpp
  src/qt/transactionview.cpp
Labels: enhancement, compatibility

#2296 refactor: Drop redundant QString calls
  src/qt/guiutil.cpp
Labels: enhancement, compatibility

#2297 depends: Bump ccache and curl
  depends/packages/curl.mk
  depends/packages/native_ccache.mk
Labels: build system, compatibility

#2287 ci: only print depends/apt output if the step fails
  ci/test_run_all.sh
Labels: enhancement, build system

#2302 depends: Update to openSSL 1.1.1l
  depends/packages/openssl.mk
Labels: build system, compatibility

#2298 rpc: Print OpenSSL version fix
  src/init.cpp
  src/qt/rpcconsole.cpp
Labels: compatibility

#2294 refactor: Optimize and Cleanup CScript::FindAndDelete
  src/script.h
  src/test/script_tests.cpp
Labels: enhancement, compatibility

#2299 wallet: Remove unused AskPassphraseDialog::Decrypt
  src/qt/askpassphrasedialog.cpp
  src/qt/askpassphrasedialog.h
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: deprecation

#2305 gui: Add back in accidentally deleted condition for UnlockStaking and Unlock cases in AskPassphraseDialog::textChanged()
  src/qt/askpassphrasedialog.cpp
Labels: bug
