Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-06, with the labels that each got.

#2153 depends: Update dependencies
  depends/packages/curl.mk
  depends/packages/qt.mk
  depends/patches/qt/fix_bigsur_drawing.patch
Labels: build System, compatibility

#2159 depends: Bump python to 3.6
  .github/workflows/ci.yml
  configure.ac
  doc/build-openbsd.md
Labels: build System, compatibility

#2157 test: Update cppcheck linter to c++17
  test/lint/extended-lint-cppcheck.sh
Labels: build System, compatibility

#2158 test: Drop Travis specific workarounds, Mention commit id in error, Fix typos, Update spellcheck ignore words
  CHANGELOG.md
  src/gridcoin/backup.cpp
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentwizardselectinputspage.cpp
  test/lint/commit-script-check.sh
  test/lint/lint-shell.sh
  test/lint/lint-spelling.ignore-words.txt
  test/lint/lint-whitespace.sh
Labels: build System

#2156 build: Remove travis references
  .github/workflows/ci.yml
  README.md
  ci/lint/06_script.sh
  ci/test/00_setup_env_arm.sh
  ci/test/03_before_install.sh
  test/lint/lint-whitespace.sh
Labels: build system, deprecation

#2167 doc: Fix "master" branch build status badge in readme
  README.md
Labels: documentation

#2144 wallet: simplify nTimeSmart calculation
  src/wallet/wallet.cpp
Labels: bug

#2170 gui: Refresh checkbox and radio button styles
  src/Makefile.qt.include
  src/qt/bitcoin.qrc
  src/qt/res/icons/checkbox_checked.svg
  src/qt/res/icons/checkbox_indeterminate.svg
  src/qt/res/icons/checkbox_unchecked.svg
  src/qt/res/icons/radio_checked.svg
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: enhancement, gui

#2169 gui: Fix Inter font rendering on Windows with FreeType
  depends/packages/qt.mk
  src/qt/bitcoin.cpp
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
Labels: enhancement, gui

#2173 build: Update native_mac_alias, Remove big sur patch file in qt recipe
  depends/packages/native_mac_alias.mk
  depends/packages/qt.mk
Labels: bug, build system, compatibility

#2147 doc: add issue templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: issue management

#2178 net: Drop support of the insecure miniUPnPc versions
  configure.ac
  src/net.cpp
Labels: deprecation

#2179 build: miniupnpc 2.2.2
  depends/packages/miniupnpc.mk
  depends/patches/miniupnpc/dont_leak_info.patch
Labels: build system, compatibility

#2175 doc: Remove CCT from README and release process docs
  doc/README.md
  doc/release-process.md
Labels: deprecation, documentation

#2163 rpc: Refresh rainbymagnitude
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
Labels: enhancement, rpc

#2174 gui: Fix assert on non-existent data directory and GUI datadir chooser corner case issues
  src/qt/bitcoin.cpp
  src/qt/intro.cpp
  src/util/system.cpp
Labels: bug

#2164 gui, rpc: Implement dynamic stakesplitting control, settings changes via rpc, and dynamic changes to sidestaking via rpc
  src/gridcoin/staking/status.cpp
  src/gridcoin/staking/status.h
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/net.cpp
  src/qt/bitcoingui.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/util/system.cpp
  src/util/system.h
Labels: enhancement, gui

#2180 gui: Fix display artifact in poll loading indicator
  src/qt/voting/polltab.cpp
Labels: bug, gui

#2185 util: optimize HexStr
  src/util/strencodings.h
Labels: enhancement, refactor

#2187 rpc, logging: Minor fixes for sidestake logging
  src/miner.cpp
  src/rpc/mining.cpp
Labels: bug

#2136 rpc: consolidatemsunspent changes.
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
Labels: enhancement, refactor, rpc

#2183 refactor: Replace "GlobalStatus" state management
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/status.cpp
  src/gridcoin/staking/status.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/miner.h
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/rpcconsole.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
  src/rpc/mining.cpp
  src/ui_interface.h
  src/util.cpp
  src/util.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: gui, refactor

#2190 rpc, util: Remove use of ArgsManager::NETWORK_ONLY for now
  src/init.cpp
  src/net.cpp
  src/util/system.h
Labels: bug

#2191 refactor: Remove obsolete pubsub method definitions
  src/net.h
Labels: deprecation

#2193 doc: Replace hidden service with onion service, Capitalize "Tor"
  src/init.cpp
  src/qt/bitcoinstrings.cpp
Labels: documentation

#2189 gui: Fix fractional scaling for dialog sizes
  src/qt/aboutdialog.cpp
  src/qt/addressbookpage.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentdialog.cpp
  src/qt/consolidateunspentwizard.cpp
  src/qt/diagnosticsdialog.cpp
  src/qt/editaddressdialog.cpp
  src/qt/forms/askpassphrasedialog.ui
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/consolidateunspentdialog.ui
  src/qt/forms/consolidateunspentwizard.ui
  src/qt/forms/consolidateunspentwizardselectdestinationpage.ui
  src/qt/forms/consolidateunspentwizardselectinputspage.ui
  src/qt/forms/consolidateunspentwizardsendpage.ui
  src/qt/forms/diagnosticsdialog.ui
  src/qt/forms/editaddressdialog.ui
  src/qt/forms/optionsdialog.ui
  src/qt/forms/rpcconsole.ui
  src/qt/forms/transactiondescdialog.ui
  src/qt/forms/voting/pollresultdialog.ui
  src/qt/forms/voting/pollwizard.ui
  src/qt/forms/voting/votewizard.ui
  src/qt/optionsdialog.cpp
  src/qt/researcher/researcherwizard.cpp
  src/qt/rpcconsole.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/transactiondescdialog.cpp
  src/qt/voting/pollresultdialog.cpp
  src/qt/voting/pollwizard.cpp
  src/qt/voting/votewizard.cpp
Labels: enhancement, gui

#2195 script: Shell script cleanups
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: bug, build system

#2194 build: set minimum required Boost to 1.58.0
  configure.ac
  gridcoinresearch.pro
Labels: build system, compatibility

#2198 qt: Remove obsolete topLevelWidget(), Remove obsolete QRegExpValidator
  src/qt/bitcoinaddressvalidator.h
  src/qt/bitcoinamountfield.cpp
  src/qt/guiutil.cpp
  src/qt/optionsdialog.cpp
Labels: deprecation

#2197 doc: Random fixes
  src/keystore.h
  src/qt/bitcoinaddressvalidator.h
  src/rpc/protocol.cpp
  src/test/bignum_tests.cpp
  src/test/netbase_tests.cpp
Labels: documentation

#2196 docs: More precise explanation of parameter onlynet
  src/init.cpp
Labels: documentation

#2199 doc: getbalance should say GRC not "btc"
  src/wallet/rpcwallet.cpp
Labels: bug, documentation

#2200 net: Add missing verification of IPv6 address in CNetAddr::GetIn6Addr…
  src/netbase.cpp
Labels: bug

#2201 log: remove deprecated db log category
  src/logging.cpp
Labels: deprecation

#2202 doc: remove duplicate line from .gitignore
  .gitignore
Labels: bug

#2203 build, util: Prevent execution for Windows versions less than Windows 7
  configure.ac
  src/compat.h
  src/init.cpp
  src/netbase.cpp
  src/qt/guiutil.cpp
  src/util/system.cpp
Labels: build system, compatibility, deprecation

#2204 build: Tweak NSIS Windows installer
  configure.ac
  share/setup.nsi.in
Labels: build system

#2205 rpc: Implement getblocksbatch
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: enhancement, rpc

#2206 Add bison in depends
  ci/test/00_setup_env.sh
  contrib/gitian-descriptors/gitian-linux.yml
  depends/README.md
Labels: build system
