Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-01, with the labels that each got.

#1995 rpc: Move rpc files to directory
  src/Makefile.am
  src/gridcoin/scraper/scraper.h
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/noui.cpp
  src/qt/bitcoingui.cpp
  src/qt/rpcconsole.cpp
  src/qt/votingdialog.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/client.h
  src/rpc/dataacq.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/protocol.cpp
  src/rpc/protocol.h
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/rpc/voting.cpp
  src/test/rpc_tests.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: compatibility

#1994 rpc: Enhance consolidateunspent and fix fee calculation
  src/qt/forms/sendcoinsdialog.ui
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
Labels: bug, enhancement

#1998 contract: Double the lookback scope of contract replay
  src/gridcoin/contract/contract.cpp
Labels: bug

#2001 accrual, rpc: Implement auditsnapshotaccruals
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/tally.cpp
  src/gridcoin/tally.h
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: bug, enhancement

#2002 Don't rely on external IP resolvers.
  src/init.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/netbase.h
Labels: enhancement

#2000 docs: add doxygen support
  .gitignore
  Makefile.am
  configure.ac
  doc/Doxyfile.in
  doc/README_doxygen.md
  doc/travis-ci.md
  src/gridcoinresearchd.cpp
Labels: documentation

#2004 consensus, accrual: Fix newbie accrual
  src/chainparams.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/tally.cpp
  src/gridcoin/tally.h
  src/main.cpp
  src/rpc/mining.cpp
Labels: bug, mandatory

#2005 ci: remove python workaround
  .github/workflows/ci.yml
Labels: build System
