Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2021-03, with the labels that each got.

#2039 voting: Add wait warning to voting tab loading message
  src/qt/votingdialog.cpp
Labels: enhancement, gui

#2040 rpc: Adds transaction hash and fees paid to consolidateunspent
  src/rpc/rawtransaction.cpp
Labels: bug, enhancement

#2036 beacon, util, gui: Fix small error in beacon db for renewals and fix snapshot download functionality
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/gridcoin.cpp
  src/gridcoin/gridcoin.h
  src/gridcoin/tally.cpp
  src/gridcoin/tally.h
  src/gridcoin/upgrade.cpp
  src/init.cpp
  src/qt/bitcoin.cpp
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
Labels: bug

#2041 gui, voting: Make some minor adjustments for VotingDialog flow
  src/qt/bitcoingui.cpp
  src/qt/votingdialog.cpp
  src/qt/votingdialog.h
Labels: enhancement, gui

#2038 build: Fix depends cross-compilation for macOS
  .github/workflows/ci.yml
  Makefile.am
  build-aux/m4/bitcoin_qt.m4
  ci/test/00_setup_env_mac.sh
  ci/test/00_setup_env_mac_host.sh
  ci/test/00_setup_env_win64.sh
  ci/test/05_before_script.sh
  configure.ac
  contrib/install_db4.sh
  contrib/macdeploy/README.md
  contrib/macdeploy/custom_dsstore.py
  contrib/macdeploy/detached-sig-apply.sh
  contrib/macdeploy/detached-sig-create.sh
  contrib/macdeploy/fancy.plist
  contrib/macdeploy/gen-sdk
  contrib/macdeploy/macdeployqtplus
  depends/Makefile
  depends/README.md
  depends/config.site.in
  depends/hosts/darwin.mk
  depends/packages/native_biplist.mk
  depends/packages/native_cdrkit.mk
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/qt59.mk
  depends/packages/zlib.mk
  depends/patches/qt/dont_hardcode_pwd.patch
  depends/patches/qt/drop_lrelease_dependency.patch
  depends/patches/qt/fix_android_jni_static.patch
  depends/patches/qt/fix_android_qmake_conf.patch
  depends/patches/qt/fix_configure_mac.patch
  depends/patches/qt/fix_mingw_cross_compile.patch
  depends/patches/qt/fix_no_printer.patch
  depends/patches/qt/fix_powerpc_libpng.patch
  depends/patches/qt/fix_qpainter_non_determinism.patch
  depends/patches/qt/fix_qt_pkgconfig.patch
  depends/patches/qt/fix_rcc_determinism.patch
  depends/patches/qt/fix_riscv64_arch.patch
  depends/patches/qt/freetype_back_compat.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/qt/no-xlib.patch
  depends/patches/qt/subdirs.pro
  depends/patches/qt/xkb-default.patch
  depends/patches/qt59/0001-Add-profile-for-cross-compilation-with-mingw-w64.patch
  depends/patches/qt59/0001-Fix-linguist-macro.patch
  depends/patches/qt59/0005-Make-sure-.pc-files-are-installed-correctly.patch
  depends/patches/qt59/0008-Fix-linking-against-shared-static-libpng.patch
  depends/patches/qt59/0011-Fix-linking-against-static-freetype2.patch
  depends/patches/qt59/0012-Fix-linking-against-static-harfbuzz.patch
  depends/patches/qt59/0013-Fix-linking-against-static-pcre.patch
  depends/patches/qt59/0021-Use-.dll.a-as-import-lib-extension.patch
  depends/patches/qt59/0030-Prevent-qmake-from-messing-static-lib-dependencies.patch
  depends/patches/qt59/fix_qt_pkgconfig.patch
  doc/README_osx.md
  doc/build-macos.md
  share/qt/Info.plist.in
  src/qt/overviewpage.h
Labels: bug, build System, enhancement

#2047 beacon, contracts: Fix sync from zero issue due to ApplyContracts problem in 5.2.1.0
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/gridcoin/gridcoin.cpp
  src/init.cpp
Labels: bug

#2048 build: Deal with Qt depends .qmake.stash file
  depends/.gitignore
  depends/packages/qt.mk
Labels: build System

#2050 gui: Add stats export reminder to beacon wizard auth page
  src/qt/forms/researcherwizardauthpage.ui
Labels: enhancement, gui

#2053 consensus, accrual: Fix accrual post hard-fork at 2197000
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/tally.cpp
  src/rpc/mining.cpp
Labels: bug, mandatory

#1997 doc: Invite users to donate to Gridcoin Foundation
  src/rpc/server.cpp
Labels: enhancement

#2054 beacon: Fix a subtle error in renewal chain walker
  src/gridcoin/tally.cpp
Labels: bug

#2056 gui: Clarify overview page "stake" field
  src/qt/forms/overviewpage.ui
Labels: enhancement

#2052 researcher: Fix "malformed CPID" status for some pool projects
  src/gridcoin/researcher.cpp
  src/test/gridcoin/researcher_tests.cpp
Labels: enhancement

#2060 lint: Misc Typos
  CHANGELOG.md
  contrib/devtools/README.md
  depends/description.md
  doc/build-windows.md
  doc/release-process.md
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/cpid.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/project.h
  src/gridcoin/quorum.cpp
  src/gridcoin/quorum.h
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/difficulty.h
  src/gridcoin/superblock.h
  src/gridcoin/tally.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/result.cpp
  src/qt/upgradeqt.h
  src/qt/votingdialog.cpp
  src/rpc/dataacq.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/test/gridcoin/contract_tests.cpp
  src/test/gridcoin/enumbytes_tests.cpp
  src/test/gridcoin/magnitude_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/test/util_tests.cpp
  src/util/time.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: documentation

#2049 rpc: Add "getburnreport" RPC function
  src/rpc/blockchain.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/script.cpp
  src/script.h
  src/wallet/wallet.cpp
Labels: enhancement, rpc

#2057 gui: Fix splash screen block height progress
  src/txdb-leveldb.cpp
  src/txdb-leveldb.h
Labels: enhancement, gui

#2058 doc: Add undocumented "-showorphans" GUI option to help text
  src/init.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionrecord.cpp
Labels: documentation

#2066 net: Reduce default connection limit back to 125
  src/net.cpp
Labels: documentation, enhancement

#2070 gui: Fix garbage placeholders in some tx notification localizations
  src/qt/locale/bitcoin_af_ZA.ts
  src/qt/locale/bitcoin_ca_ES.ts
  src/qt/locale/bitcoin_cs.ts
  src/qt/locale/bitcoin_da.ts
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_en.ts
  src/qt/locale/bitcoin_eo.ts
  src/qt/locale/bitcoin_es.ts
  src/qt/locale/bitcoin_es_CL.ts
  src/qt/locale/bitcoin_es_DO.ts
  src/qt/locale/bitcoin_et.ts
  src/qt/locale/bitcoin_fi.ts
  src/qt/locale/bitcoin_fr.ts
  src/qt/locale/bitcoin_fr_CA.ts
  src/qt/locale/bitcoin_gl.ts
  src/qt/locale/bitcoin_hr.ts
  src/qt/locale/bitcoin_hu.ts
  src/qt/locale/bitcoin_id_ID.ts
  src/qt/locale/bitcoin_it.ts
  src/qt/locale/bitcoin_la.ts
  src/qt/locale/bitcoin_lt.ts
  src/qt/locale/bitcoin_lv_LV.ts
  src/qt/locale/bitcoin_nb.ts
  src/qt/locale/bitcoin_nl.ts
  src/qt/locale/bitcoin_pam.ts
  src/qt/locale/bitcoin_pl.ts
  src/qt/locale/bitcoin_pt_BR.ts
  src/qt/locale/bitcoin_pt_PT.ts
  src/qt/locale/bitcoin_ro_RO.ts
  src/qt/locale/bitcoin_ru.ts
  src/qt/locale/bitcoin_sk.ts
  src/qt/locale/bitcoin_sl_SI.ts
  src/qt/locale/bitcoin_tr.ts
  src/qt/locale/bitcoin_zh_CN.ts
Labels: bug

#2074 build; openssl patch
  depends/packages/openssl.mk
Labels: build System

#2069 beacon: Cull beacon db memory (passivation)
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/tally.cpp
  src/rpc/mining.cpp
  src/test/gridcoin/beacon_tests.cpp
Labels: enhancement

#2068 gui: Avoid refreshing GUI researcher status while out-of-sync
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/qt/researcher/researcherwizardbeaconpage.cpp
  src/qt/researcher/researcherwizardsummarypage.cpp
Labels: enhancement, gui

#2080 net: Clean up mandatory protocol version transition
  src/main.cpp
  src/version.h
Labels: deprecation

#2082 build: Patch libzip to fix mingw compile regression for mingw 9.2+
  depends/packages/libzip.mk
  depends/patches/libzip/compat.h.patch
Labels: build System

#2083 translation: Translate '/src/qt/locale/bitcoin_en.ts' in 'pt_PT'
  src/qt/locale/bitcoin_pt_PT.ts
Labels: translations

#2076 log: Adjust logging
  src/init.cpp
  src/main.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: enhancement
