Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-05, with the labels that each got.

#2507 util: Change default -dbcache to 100 MB and also implement -txindexdbcache
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/init.cpp
  src/wallet/db.cpp
Labels: enhancement

#2508 rpc, util, consensus: Implement exception handling framework for MRC and fix ValidateMRC to deal with testnet consensus issue
  src/gridcoin/mrc.cpp
  src/gridcoin/mrc.h
  src/gridcoin/staking/kernel.cpp
  src/main.cpp
  src/rpc/blockchain.cpp
  src/test/gridcoin/mrc_tests.cpp
Labels: enhancement, gui, rpc

#2512 consensus: Move DoS into contract validators to allow variability of DoS based on context and further fixes to ValidateMRC
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/gridcoin/contract/handler.h
  src/gridcoin/mrc.cpp
  src/gridcoin/mrc.h
  src/gridcoin/project.h
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/registry.h
  src/main.cpp
  src/main.h
  src/miner.cpp
Labels: bug, enhancement, mandatory

#2514 utils: run commands using utf-8 string on Windows
  src/util.cpp
Labels: bug, compatibility

#2516 prevector: enforce is_trivially_copyable_v
  src/prevector.h
Labels: enhancement

#2506 gui: Modify VerifyTCPPort to use the status of CheckOutboundConnectionCount
  src/qt/diagnosticsdialog.cpp
  src/qt/diagnosticsdialog.h
Labels: enhancement, gui

#2509 lockedpool: When possible, use madvise to avoid including sensitive information in core dumps
  src/support/lockedpool.cpp
Labels: bug, compatibility

#2513 gui: Initial implementation of GUI MRC submission form
  src/Makefile.qt.include
  src/gridcoin/mrc.cpp
  src/gridcoin/mrc.h
  src/main.cpp
  src/node/ui_interface.cpp
  src/node/ui_interface.h
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/mrcrequestpage.ui
  src/qt/forms/overviewpage.ui
  src/qt/mrcmodel.cpp
  src/qt/mrcmodel.h
  src/qt/mrcrequestpage.cpp
  src/qt/mrcrequestpage.h
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
  src/rpc/blockchain.cpp
Labels: enhancement, gui

#2439 build: Port over Bitcoin's translation docs
  doc/translation_process.md
  doc/translation_strings_policy.md
Labels: build system

#2518 Miner Logger bug fix
  src/wallet/wallet.cpp
Labels: bug

#2519 key: properly parse short DER private keys
  src/key.cpp
Labels: bug
