Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-03, with the labels that each got.

#2447 test: Add TrimString(...) tests
  src/test/util_tests.cpp
Labels: enhancement, compatibility

#2449 [tests] Add dead code detection
  ci/lint/04_install.sh
  test/lint/lint-python-dead-code.sh
Labels: enhancement, build system, compatibility

#2451 net: Do not add random inbound peers to addrman
  src/main.cpp
Labels: enhancement, compatibility

#2452 refactor: Replace memset calls with array initialization
  src/protocol.cpp
  src/protocol.h
Labels: enhancement, compatibility

#2455 refactor: Changed some parameters from pass by value to pass by reference
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
Labels: enhancement

#2448 util: skip trying to set the locale on NetBSD
  src/util/system.cpp
Labels: compatibility

#2462 build: change bundle id
  share/qt/Info.plist.in
Labels: bug

#2461 ci, cd: improve caching
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  cd/00_setup_env.sh
  ci/test/00_setup_env.sh
Labels: enhancement, build system

#2465 contrib: port recent macdeployqtplus changes
  contrib/macdeploy/macdeployqtplus
Labels: enhancement, build system

#2464 test: Test for expected return values when calling functions returning a success code
  src/test/dos_tests.cpp
  src/test/multisig_tests.cpp
Labels: enhancement, build system

#2460 build: Improve error message when pkg-config is not installed
  configure.ac
Labels: enhancement, build system

#2463 test: Bump shellcheck, mypy versions
  ci/lint/04_install.sh
Labels: enhancement, build system, compatibility

#2466 build: Update depends packages (expat, fontconfig, freetype, libXau, libxcb, xcb_proto, xproto)
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/freetype.mk
  depends/packages/libXau.mk
  depends/packages/libxcb.mk
  depends/packages/xcb_proto.mk
  depends/packages/xproto.mk
  depends/patches/fontconfig/gperf_header_regen.patch
Labels: build system, compatibility

#2467 test: Add explicit references to related CVE's in comments
  src/main.cpp
  src/validation.cpp
Labels: documentation

#2453 net: Do not propagate obviously poor addresses onto the network
  src/addrman.cpp
Labels: enhancement, compatibility

#2469 ci: Fix CI build title to reflect that we are building for bionic, not xenial
  .github/workflows/ci.yml
Labels: build system, documentation

#2470 test: Add testing of ParseInt/ParseUInt edge cases with leading +/-/0:s
  src/test/util_tests.cpp
Labels: enhancement, test suite

#2472 lint: Fix misc typos
  src/init.cpp
  src/rpc/blockchain.cpp
  src/test/gridcoin/mrc_tests.cpp
  src/test/util_tests.cpp
Labels: bug

#2476 build: Fix several minor linter errors
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/main.cpp
  src/miner.cpp
  src/qt/bitcoin.cpp
  src/test/gridcoin/mrc_tests.cpp
  src/tinyformat.h
  src/util/time.cpp
  test/lint/lint-format-strings.py
  test/lint/lint-format-strings.sh
  test/lint/lint-spelling.ignore-words.txt
Labels: build system, test suite

#2475 lint: run mypy over contrib/devtools
  contrib/devtools/circular-dependencies.py
  contrib/devtools/symbol-check.py
  test/lint/lint-python.sh
Labels: build system, compatibility
