Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-06, with the labels that each got.

#2521 init: fix daemon forking
  configure.ac
  contrib/init/gridcoinresearchd.service
  src/Makefile.am
  src/fs.cpp
  src/gridcoinresearchd.cpp
  src/init.cpp
  src/init.h
  src/qt/bitcoin.cpp
  src/util.cpp
  src/util.h
  src/util/syserror.cpp
  src/util/syserror.h
  src/util/tokenpipe.cpp
  src/util/tokenpipe.h
Labels: bug, enhancement

#2526 gui: New MRC request icon
  src/qt/res/icons/tx_contract_mrc.svg
Labels: enhancement, gui

#2522 mandatory, voting: Implement poll type validation in protocol
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/params.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/contract.cpp
  src/gridcoin/contract/contract.h
  src/gridcoin/contract/handler.h
  src/gridcoin/mrc.cpp
  src/gridcoin/mrc.h
  src/gridcoin/project.h
  src/gridcoin/support/block_finder.cpp
  src/gridcoin/support/block_finder.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/builders.h
  src/gridcoin/voting/claims.h
  src/gridcoin/voting/fwd.h
  src/gridcoin/voting/payloads.h
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/poll.h
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/registry.h
  src/gridcoin/voting/result.cpp
  src/gridcoin/voting/result.h
  src/init.cpp
  src/main.cpp
  src/miner.cpp
  src/qt/forms/voting/pollcard.ui
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/voting/poll_types.cpp
  src/qt/voting/poll_types.h
  src/qt/voting/pollcard.cpp
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/pollwizarddetailspage.cpp
  src/qt/voting/pollwizardtypepage.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
  src/rpc/client.cpp
  src/rpc/voting.cpp
Labels: bug, enhancement, mandatory, gui, rpc

#2525 gui, voting: Implement poll additional fields gui components
  src/Makefile.qt.include
  src/gridcoin/voting/poll.cpp
  src/gridcoin/voting/poll.h
  src/qt/forms/voting/additionalfieldstableview.ui
  src/qt/forms/voting/polldetails.ui
  src/qt/forms/voting/pollwizarddetailspage.ui
  src/qt/forms/voting/pollwizardprojectpage.ui
  src/qt/voting/additionalfieldstablemodel.cpp
  src/qt/voting/additionalfieldstablemodel.h
  src/qt/voting/additionalfieldstableview.cpp
  src/qt/voting/additionalfieldstableview.h
  src/qt/voting/poll_types.cpp
  src/qt/voting/poll_types.h
  src/qt/voting/polldetails.cpp
  src/qt/voting/polldetails.h
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/pollwizarddetailspage.cpp
  src/qt/voting/pollwizarddetailspage.h
  src/qt/voting/pollwizardprojectpage.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
Labels: enhancement, gui
