Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-10, with the labels that each got.

#2579 build: Require gcc8 on Ubuntu Bionic to enable C++17 features
  ci/test/00_setup_env_native_old.sh
  doc/build-unix.md
Labels: build system, compatibility

#2564 util: Replace use of locale dependent atoi(…) with locale-independent std::from_chars(…) (C++17)
  src/test/script_tests.cpp
  src/test/util_tests.cpp
  src/util/strencodings.cpp
  src/util/strencodings.h
  src/util/system.cpp
  test/lint/lint-locale-dependence.sh
Labels: compatibility, deprecation

#2581 translation: Translation updates
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
Labels: translations

#2583 depends: update urls for dmg tools
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
Labels: build system, compatibility

#2584 doc: Fix link to MurmurHash3.cpp (moved from Google Code to Github)
  src/hash.cpp
Labels: documentation

#2585 refactor: Remove unused CDataStream::rdbuf method
  src/streams.h
Labels: compatibility, deprecation

#2591 fix help text for `revokebeacon` command
  src/rpc/blockchain.cpp
Labels: bug, documentation

#2590 util: Fix spelling error in gridcoinresearchd.cpp
  src/gridcoinresearchd.cpp
Labels: bug

#2588 depends: always use correct ar for win qt build
  depends/packages/qt.mk
Labels: build system, compatibility

#2587 fs: fully initialize `_OVERLAPPED` for win32
  src/fs.cpp
Labels: compatibility

#2573 util: Diagnose Lib Version #1
  src/Makefile.am
  src/gridcoin/staking/difficulty.h
  src/qt/diagnosticsdialog.cpp
  src/qt/diagnosticsdialog.h
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/diagnose.cpp
  src/wallet/diagnose.h
  src/wallet/rpcwallet.cpp
  test/lint/lint-includes.sh
Labels: enhancement, refactor

#2586 Use ReadLE64 in uint256::GetUint64 instead of duplicating logic
  src/uint256.h
Labels: compatibility, refactor
