Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-01, with the labels that each got.

#2420 gui: Enable masking of cpid in privacy mode
  src/qt/overviewpage.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: enhancement, gui

#2421 doc: Update license year range to 2022
  COPYING
  configure.ac
Labels: documentation

#2424 util: clean obsolete config keys
  src/gridcoin/gridcoin.cpp
  src/gridcoin/gridcoin.h
  src/init.cpp
Labels: enhancement, deprecation

#2426 net: Implement an upper limit of 950 for max network connections
  src/init.cpp
  src/net.cpp
Labels: bug

#2430 staking, gui: Fixes a missing miner search interval update for no coins corner case
  src/miner.cpp
Labels: bug, gui
