Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-08, with the labels that each got.

#2532 net: Fix some benign races (backport)
  src/addrman.h
  src/net.h
Labels: bug, compatibility

#2533 net: Add and document network messages in protocol.h (backport)
  src/alert.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/main.cpp
  src/net.cpp
  src/protocol.cpp
  src/protocol.h
Labels: compatibility

#2555 Define MAX_DIGITS_BTC for magic number in BitcoinUnits::format
  src/qt/bitcoinunits.cpp
Labels: compatibility, refactor

#2556 rpc: fix invalid parameter error codes for {sign,verify}message RPCs
  src/wallet/rpcwallet.cpp
Labels: bug, compatibility

#2557 scripted-diff: Drop Darwin version for better maintainability
  cd/00_setup_env_mac.sh
  ci/test/00_setup_env_mac.sh
  ci/test/00_setup_env_mac_host.sh
  contrib/macdeploy/README.md
  depends/README.md
Labels: build system, compatibility

#2562 refactor: remove unused c-string variant of atoi64()
  src/util/strencodings.cpp
  src/util/strencodings.h
Labels: compatibility, deprecation

#2560 build: Fix x86_64 <-> arm64 cross-compiling for macOS
  depends/builders/darwin.mk
Labels: bug, build system, compatibility

#2567 rpc, mrc: Fix field name and initialization of mrc_fees_to_staker
  src/gridcoin/claim.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/rpc/blockchain.cpp
Labels: bug, rpc

#2569 gui: Add missing resizeTableColumns to fix send address book column widths
  src/qt/sendcoinsentry.cpp
  src/qt/signverifymessagedialog.cpp
Labels: bug, gui
