Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-12, with the labels that each got.

#2610 depends: fix OpenSSL for Darwin builds
  depends/builders/darwin.mk
  depends/packages/openssl.mk
Labels: build system, compatibility

#2561 net: Turn net structures into dumb storage classes (backport)
  src/Makefile.am
  src/Makefile.test.include
  src/addrman.cpp
  src/addrman.h
  src/init.cpp
  src/net.cpp
  src/netaddress.cpp
  src/netaddress.h
  src/netbase.cpp
  src/netbase.h
  src/protocol.h
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/test/addrman_tests.cpp
  src/test/net_tests.cpp
  src/test/netbase_tests.cpp
Labels: compatibility, refactor

#2609 build: Include native_X.mk before X.mk
  depends/funcs.mk
Labels: build system, compatibility

#2617 gui: don't show datadir error msgbox if arg isn't specified
  src/gridcoin/researcher.cpp
Labels: enhancement
