Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-11, with the labels that each got.

#2597 util: Diagnose lib - Implement changes to solve crash on some Boost 1.66 machines
  src/wallet/diagnose.cpp
  src/wallet/diagnose.h
  test/lint/lint-includes.sh
Labels: refactor

#2592 util: Make Parse{Int,UInt}{32,64} use locale independent std::from_chars(…) (C++17) instead of locale dependent strto{l,ll,ul,ull}
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/upgrade.cpp
  src/rpc/protocol.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/test/util_tests.cpp
  src/util/strencodings.cpp
  src/util/strencodings.h
  src/util/system.cpp
  src/wallet/wallet.h
  test/lint/lint-locale-dependence.sh
Labels: compatibility, deprecation, refactor

#2593 build: don't set PORT=no in config.site
  depends/config.site.in
Labels: build system, compatibility

#2595 build: Replace `which` command with `command -v`
  depends/hosts/mingw32.mk
Labels: build system, compatibility

#2596 build: update ax_cxx_compile_stdcxx to serial 14
  build-aux/m4/ax_cxx_compile_stdcxx.m4
Labels: build system, compatibility

#2594 contrib: Check for `patch` command, Check for `wget` command
  contrib/install_db4.sh
Labels: build system, compatibility

#2536 util: modify Win32LockedPageAllocator to query windows for limit.
  src/support/lockedpool.cpp
Labels: enhancement, compatibility

#2598 gui: Changed the unlocked for staking only icons to green
  src/qt/res/icons/icons_dark/status_encryption_unlocked.svg
  src/qt/res/icons/icons_light/status_encryption_unlocked.svg
Labels: enhancement, gui

#2582 build: Check std::system for -[alert|block|wallet]notify
  configure.ac
  src/alert.cpp
  src/init.cpp
  src/main.cpp
  src/util.cpp
  src/util.h
  src/wallet/wallet.cpp
Labels: build system, compatibility

#2602 gui: Changed the wording on the tooltip for the address book
  src/qt/forms/addressbookpage.ui
  src/qt/locale/bitcoin_en.ts
Labels: bug, gui

#2601 build: pass win32-dll to LT_INIT()
  configure.ac
Labels: build system, compatibility

#2600 build: minor cleanups to native_clang package
  depends/packages/native_clang.mk
Labels: build system, compatibility

#2603 util: restore translations to diagnostics
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
  src/wallet/diagnose.cpp
  src/wallet/diagnose.h
Labels: translations

#2606 build: update CI for linter and actions version
  .github/workflows/ci.yml
  CHANGELOG.md
  ci/lint/04_install.sh
  src/gridcoinresearchd.cpp
  test/lint/lint-spelling.ignore-words.txt
Labels: build system, compatibility

#2605 gui, voting: Implement information for wallet holder's votes on poll info cards
  src/gridcoin/voting/result.cpp
  src/gridcoin/voting/result.h
  src/qt/forms/voting/pollcard.ui
  src/qt/voting/pollcard.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
Labels: enhancement, gui

#2607 refactor: Fix problems found by valgrind
  src/keystore.h
  src/qt/researcher/researchermodel.cpp
Labels: bug, refactor

#2608 gui: Update translations
  src/qt/locale/bitcoin_af_ZA.ts
  src/qt/locale/bitcoin_ca.ts
  src/qt/locale/bitcoin_ca@valencia.ts
  src/qt/locale/bitcoin_ca_ES.ts
  src/qt/locale/bitcoin_cs.ts
  src/qt/locale/bitcoin_cy.ts
  src/qt/locale/bitcoin_da.ts
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_eo.ts
  src/qt/locale/bitcoin_es.ts
  src/qt/locale/bitcoin_es_CL.ts
  src/qt/locale/bitcoin_es_DO.ts
  src/qt/locale/bitcoin_es_MX.ts
  src/qt/locale/bitcoin_es_UY.ts
  src/qt/locale/bitcoin_et.ts
  src/qt/locale/bitcoin_eu_ES.ts
  src/qt/locale/bitcoin_fi.ts
  src/qt/locale/bitcoin_fr.ts
  src/qt/locale/bitcoin_fr_CA.ts
  src/qt/locale/bitcoin_gl.ts
  src/qt/locale/bitcoin_hr.ts
  src/qt/locale/bitcoin_hu.ts
  src/qt/locale/bitcoin_id_ID.ts
  src/qt/locale/bitcoin_it.ts
  src/qt/locale/bitcoin_la.ts
  src/qt/locale/bitcoin_lt.ts
  src/qt/locale/bitcoin_lv_LV.ts
  src/qt/locale/bitcoin_ms_MY.ts
  src/qt/locale/bitcoin_nb.ts
  src/qt/locale/bitcoin_nl.ts
  src/qt/locale/bitcoin_pam.ts
  src/qt/locale/bitcoin_pl.ts
  src/qt/locale/bitcoin_pt_BR.ts
  src/qt/locale/bitcoin_pt_PT.ts
  src/qt/locale/bitcoin_ro_RO.ts
  src/qt/locale/bitcoin_ru.ts
  src/qt/locale/bitcoin_sk.ts
  src/qt/locale/bitcoin_sl_SI.ts
  src/qt/locale/bitcoin_sq.ts
  src/qt/locale/bitcoin_sv.ts
  src/qt/locale/bitcoin_tr.ts
  src/qt/locale/bitcoin_vi.ts
  src/qt/locale/bitcoin_zh_CN.ts
Labels: translations
