Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-07, with the labels that each got.

#2528 scraper: Change open mode from append to truncate for auth file
  src/gridcoin/scraper/scraper.cpp
Labels: bug

#2529 gui: New mrc contract icon try #2
  src/qt/res/icons/tx_contract_mrc.svg
Labels: enhancement, gui

#2530 gui: Remove white outlines on MRC icon
  src/qt/res/icons/tx_contract_mrc.svg
Labels: enhancement, gui

#2538 log: Use consistent wording in random.cpp log
  src/random.cpp
Labels: bug

#2537 build, qt: Fix `QMAKE_CXXFLAGS` expression for `mingw32` host
  depends/packages/qt.mk
Labels: bug, build system, compatibility

#2535 logging: fix logging empty thread name
  src/logging.cpp
Labels: bug, compatibility

#2542 trivial: fix comment in account header guard
  src/gridcoin/account.h
Labels: bug, documentation

#2541 lint: Use newer versions of our lint packages, remove yq
  ci/lint/04_install.sh
Labels: build system, compatibility

#2539 [1/2] validation: move CBlock validation methods to validation.cpp
  src/dbwrapper.cpp
  src/gridcoin/staking/kernel.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/validation.cpp
  src/validation.h
Labels: mandatory, compatibility, refactor

#2543 gui: Implement proportional column resizing for Addressbook with memory
  src/qt/addressbookpage.cpp
  src/qt/addressbookpage.h
  src/qt/addresstablemodel.h
  src/qt/bitcoingui.cpp
  src/qt/favoritespage.cpp
  src/qt/favoritespage.h
  src/qt/receivecoinspage.cpp
  src/qt/receivecoinspage.h
Labels: enhancement, gui

#2544 build: Restrict check for CRC32C intrinsic to aarch64
  configure.ac
Labels: bug, build system, compatibility

#2545 build: force CRCCheck in Windows installer
  share/setup.nsi.in
Labels: bug, build system

#2547 qt: Prefix makefile variables with QT_
  src/Makefile.qt.include
Labels: build system, compatibility

#2550 build: remove build stubs for external leveldb
  configure.ac
  src/Makefile.am
  src/Makefile.leveldb.include
Labels: build system, compatibility

#2549 build, refactor: Improve package version usage
  depends/packages/boost.mk
  depends/packages/expat.mk
  depends/packages/openssl.mk
Labels: build system, compatibility

#2548 build: minor boost tidyups
  depends/packages/boost.mk
Labels: build system, compatibility

#2552 test: remove obsolete check sig test
  src/test/dos_tests.cpp
Labels: compatibility, test suite

#2551 consensus, rpc: Kermit's mom hardfork (2671700)
  .github/workflows/ci.yml
  src/chainparams.cpp
  src/chainparams.h
  src/rpc/client.cpp
  src/rpc/net.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcdump.cpp
Labels: mandatory, rpc

#2554 refactor: Kermits mom post RC1 cleanup
  src/chainparams.h
  src/gridcoin/mrc.cpp
  src/gridcoin/tally.cpp
  src/init.cpp
  src/miner.cpp
  src/validation.cpp
Labels: refactor
