Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2022-02, with the labels that each got.

#2436 contrib: install_db4: use local config.guess/sub
  contrib/install_db4.sh
Labels: build system, compatibility

#2438 gui: Add uiInterface.BeaconChanged() call after ActivatePending
  src/main.cpp
Labels: bug, gui

#2427 net: Hard Coded Seed Node Cleanup
  src/init.cpp
  src/net.cpp
Labels: deprecation

#2428 build: fix unoptimized libraries in depends
  depends/packages/bdb.mk
  depends/packages/bdb53.mk
  depends/packages/boost.mk
Labels: bug, build system

#2429 build: don't use deprecated brew package names
  configure.ac
Labels: deprecation

#2440 qt: fix shutdown on MacOS
  src/Makefile.qt.include
  src/init.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/macdockiconhandler.h
  src/qt/macdockiconhandler.mm
Labels: bug, compatibility

#2443 gui: Update copyright year to 2022 for Gridcoin About dialog box
  src/qt/aboutdialog.cpp
Labels: bug, gui

#2441 rpc: Change type field in ListTransactions to lower case
  src/wallet/rpcwallet.cpp
Labels: bug, rpc
