Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-11, with the labels that each got.

#2711 rpc: Change capitalization, remove whitespace of rpc keys
  src/rpc/blockchain.cpp
Labels: enhancement, rpc

#2713 ci: bump MacOS version to 12
  .github/workflows/ci.yml
Labels: build system, compatibility

#2715 gui, projects: Implement greylist state for projects in GUI projects table
  src/qt/researcher/projecttablemodel.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: enhancement, gui
