Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-03, with the labels that each got.

#2645 gui: Change MRC too soon to submit error to be less confusing
  src/qt/mrcmodel.cpp
Labels: enhancement, gui

#2643 build(nsis): Write registry keys to HKLM instead of HKCU, Install shortcuts for all users, Fix INSTALLDIR removal bug
  share/setup.nsi.in
Labels: bug

#2647 gui: Fix TransactionRecord::decomposeTransaction to properly display self-sidestake
  src/qt/transactionrecord.cpp
Labels: bug, gui

#2646 rpc: add `getnodeaddresses`
  src/rpc/client.cpp
  src/rpc/net.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: enhancement, compatibility

#2649 rpc: Fixed the RPC error when running `help voting` while syncing
  src/rpc/voting.cpp
Labels: bug, rpc

#2651 consensus: Add new checkpoints
  src/chainparams.cpp
Labels: security

#2640 gui: Fix wallet overview displaying lower-case poll name
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/registry.h
Labels: enhancement

#2653 build: Fix compilation with GCC 13
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/crypter.cpp
  src/dbwrapper.cpp
  src/gridcoin/accrual/snapshot.h
  src/gridcoin/appcache.cpp
  src/gridcoin/mrc.h
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoin/upgrade.cpp
  src/gridcoin/upgrade.h
  src/gridcoin/voting/fwd.h
  src/gridcoinresearchd.cpp
  src/primitives/transaction.h
  src/qt/bitcoin.cpp
  src/qt/rpcconsole.cpp
  src/rpc/blockchain.cpp
  src/rpc/blockchain.h
  src/rpc/client.cpp
  src/rpc/dataacq.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/rpc/voting.cpp
  src/script.cpp
  src/script.h
  src/support/lockedpool.cpp
  src/support/lockedpool.h
  src/test/allocator_tests.cpp
  src/test/rpc_tests.cpp
  src/test/transaction_tests.cpp
  src/univalue/include/univalue.h
  src/util/bip32.h
  src/util/string.h
  src/util/system.cpp
  src/validation.cpp
  src/wallet/db.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: build system, compatibility

#2613 util: move threadinterrupt.{cpp,h} to util
  src/Makefile.am
  src/util/threadinterrupt.cpp
  src/util/threadinterrupt.h
  src/util/time.h
Labels: compatibility

#2642 Fix and optimize ResendWalletTransactions
  src/init.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.h
Labels: bug, enhancement

#2654 rpc: Formatting - typo correction rpc help for listresearcheraccounts
  src/rpc/mining.cpp
Labels: bug, documentation

#2658 locale: Update translations prior to release (phase 2/2)
  src/qt/locale/bitcoin_af_ZA.ts
  src/qt/locale/bitcoin_ar.ts
  src/qt/locale/bitcoin_be_BY.ts
  src/qt/locale/bitcoin_ca.ts
  src/qt/locale/bitcoin_ca@valencia.ts
  src/qt/locale/bitcoin_ca_ES.ts
  src/qt/locale/bitcoin_cs.ts
  src/qt/locale/bitcoin_da.ts
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_el_GR.ts
  src/qt/locale/bitcoin_eo.ts
  src/qt/locale/bitcoin_es.ts
  src/qt/locale/bitcoin_es_CL.ts
  src/qt/locale/bitcoin_es_DO.ts
  src/qt/locale/bitcoin_et.ts
  src/qt/locale/bitcoin_fa.ts
  src/qt/locale/bitcoin_fa_IR.ts
  src/qt/locale/bitcoin_fi.ts
  src/qt/locale/bitcoin_fr.ts
  src/qt/locale/bitcoin_fr_CA.ts
  src/qt/locale/bitcoin_gl.ts
  src/qt/locale/bitcoin_he.ts
  src/qt/locale/bitcoin_hr.ts
  src/qt/locale/bitcoin_hu.ts
  src/qt/locale/bitcoin_id_ID.ts
  src/qt/locale/bitcoin_it.ts
  src/qt/locale/bitcoin_ja.ts
  src/qt/locale/bitcoin_ka.ts
  src/qt/locale/bitcoin_ko_KR.ts
  src/qt/locale/bitcoin_la.ts
  src/qt/locale/bitcoin_lv_LV.ts
  src/qt/locale/bitcoin_nb.ts
  src/qt/locale/bitcoin_nl.ts
  src/qt/locale/bitcoin_pam.ts
  src/qt/locale/bitcoin_pl.ts
  src/qt/locale/bitcoin_pt_BR.ts
  src/qt/locale/bitcoin_pt_PT.ts
  src/qt/locale/bitcoin_ro_RO.ts
  src/qt/locale/bitcoin_ru.ts
  src/qt/locale/bitcoin_sk.ts
  src/qt/locale/bitcoin_sl_SI.ts
  src/qt/locale/bitcoin_sv.ts
  src/qt/locale/bitcoin_tr.ts
  src/qt/locale/bitcoin_uk.ts
  src/qt/locale/bitcoin_vi.ts
  src/qt/locale/bitcoin_zh_CN.ts
  src/qt/locale/bitcoin_zh_TW.ts
Labels: translations

#2659 gui: Enhance MRC request form to avoid fee boost field confusion
  src/qt/forms/mrcrequestpage.ui
  src/qt/mrcrequestpage.cpp
Labels: enhancement, gui

#2660 contrib: add nix file for compilation environment
  contrib/default.nix
Labels: enhancement, build system

#2668 banman: use GetPerformanceCounter instead of GetRandBytes
  src/addrdb.cpp
Labels: bug

#2669 util: Implement workaround for backupwallet to deal with Boost 1.74 regression on copy_file
  src/gridcoin/backup.cpp
Labels: bug

#2671 gui: Add one minute QTimer to update beacon age/expiration in tooltip
  src/qt/bitcoingui.cpp
Labels: enhancement, gui
