Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-07, with the labels that each got.

#2690 wallet: SecureString to allow null characters
  src/qt/askpassphrasedialog.cpp
  src/wallet/rpcwallet.cpp
Labels: compatibility, security

#2676 build: Initial CMake support
  .github/workflows/cmake-ci.yml
  .gitignore
  CMakeLists.txt
  README.md
  build-aux/cmake/CheckSSE.cmake
  build-aux/cmake/CheckStrerrorR.cmake
  build-aux/cmake/ExternalLibraryHelper.cmake
  build-aux/cmake/FindAtomics.cmake
  build-aux/cmake/FindBerkeleyDB.cmake
  build-aux/cmake/FindRt.cmake
  build-aux/cmake/VersionFromGit.cmake
  build-aux/cmake/json2header.cmake
  build-aux/cmake/txt2header.cmake
  contrib/default.nix
  doc/CMakeLists.txt
  doc/README.md
  doc/build-freebsd.md
  doc/build-macos.md
  doc/build-openbsd.md
  doc/build-unix.md
  doc/build-windows.md
  doc/cmake-options.md
  doc/readme-qt.rst
  doc/release-process.md
  src/CMakeLists.txt
  src/bdb53/CMakeLists.txt
  src/config/.empty
  src/config/gridcoin-config.h.cmake.in
  src/crypto/CMakeLists.txt
  src/gridcoin/voting/registry.cpp
  src/gridcoin/voting/result.cpp
  src/leveldb/CMakeLists.txt
  src/obj/build.h.in
  src/qt/CMakeLists.txt
  src/qt/locale/CMakeLists.txt
  src/qt/test/CMakeLists.txt
  src/rpc/voting.cpp
  src/script.cpp
  src/serialize.h
  src/test/CMakeLists.txt
  src/test/data/CMakeLists.txt
  src/test/xxd/xxd.c
  src/univalue/CMakeLists.txt
  test/lint/lint-format-strings.sh
  test/lint/lint-spelling.ignore-words.txt
Labels: enhancement, build system

#2693 doc: Update link to Discord server
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  doc/README.md
Labels: documentation

#2692 depends: Bump dependencies
  depends/packages/curl.mk
  depends/packages/expat.mk
  depends/packages/qrencode.mk
  depends/packages/qt.mk
  depends/packages/zlib.mk
  depends/patches/qt/dont_hardcode_x86_64.patch
  depends/patches/qt/fix_android_jni_static.patch
  depends/patches/qt/fix_limits_header.patch
Labels: build system, compatibility
