Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-10, with the labels that each got.

#2705 build, crypto, script: remove most of OpenSSL usage
  src/Makefile.am
  src/Makefile.test.include
  src/arith_uint256.cpp
  src/arith_uint256.h
  src/bignum.h
  src/crypto/CMakeLists.txt
  src/gridcoin/cpid.cpp
  src/gridcoin/md5.c
  src/gridcoin/md5.h
  src/gridcoin/quorum.cpp
  src/gridcoin/researcher.cpp
  src/gridcoin/staking/difficulty.cpp
  src/gridcoin/staking/kernel.cpp
  src/gridcoin/superblock.cpp
  src/gridcoin/upgrade.cpp
  src/main.cpp
  src/miner.cpp
  src/pbkdf2.cpp
  src/pbkdf2.h
  src/script.cpp
  src/script.h
  src/test/CMakeLists.txt
  src/test/bignum_tests.cpp
  src/test/crypto_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/validation.cpp
Labels: compatibility, deprecation

#2708 gui: Fix filter by type in Transaction View
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactionview.cpp
Labels: bug, gui

#2709 gui, voting: Implement poll result caching and poll stale indicator
  src/gridcoin/voting/registry.cpp
  src/node/ui_interface.cpp
  src/node/ui_interface.h
  src/qt/forms/voting/pollcard.ui
  src/qt/res/stylesheets/dark_stylesheet.qss
  src/qt/res/stylesheets/light_stylesheet.qss
  src/qt/voting/pollcard.cpp
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
Labels: enhancement, gui
