Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-04, with the labels that each got.

#2672 install: Enhance windows installer - detect running gridcoinresearch(d).exe and ask to close before continuing
  share/setup.nsi.in
Labels: enhancement

#2675 build: allow system bdb
  configure.ac
  src/Makefile.am
  src/Makefile.qt.include
  src/Makefile.qttest.include
  src/Makefile.test.include
Labels: enhancement, build system, compatibility

#2680 wallet, rpc: Add missing assignment of fCompressed in dumpprivkey
  src/key.cpp
  src/keystore.h
Labels: bug

#2682 key, rpc: fix key parsing
  src/key.cpp
  src/rpc/net.cpp
  src/wallet/rpcdump.cpp
Labels: bug, rpc

#2684 diagnostics: fix missing arg in ETTS warning
  src/wallet/diagnose.h
Labels: bug, refactor

#2683 Resize Header Column with Additional Text
  src/qt/researcher/projecttablemodel.cpp
Labels: gui
