Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-12, with the labels that each got.

#2716 gui, poll: Implement poll expiration reminders
  src/gridcoin/voting/result.cpp
  src/gridcoin/voting/result.h
  src/main.cpp
  src/main.h
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/optionsdialog.ui
  src/qt/forms/voting/pollcard.ui
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/voting/pollcard.cpp
  src/qt/voting/pollcardview.cpp
  src/qt/voting/pollcardview.h
  src/qt/voting/polltab.cpp
  src/qt/voting/polltab.h
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
  src/qt/voting/votingpage.cpp
  src/qt/voting/votingpage.h
Labels: enhancement, gui, feature request

#2717 util: remove WSL 1 workaround in fs
  src/fs.cpp
Labels: compatibility, deprecation

#2718 depends: make fontconfig build under clang-16
  depends/packages/fontconfig.mk
Labels: build system, compatibility

#2719 depends: no-longer nuke libc++abi.so* in native_clang package
  depends/packages/native_clang.mk
Labels: build system, compatibility

#2721 Silence `-Wcast-function-type` warning
  src/qt/winshutdownmonitor.cpp
Labels: build system, compatibility

#2722 build: Use newest `config.{guess,sub}` available
  autogen.sh
Labels: build system, compatibility

#2723 refactor: use the try_lock result in TryEnter
  src/sync.h
Labels: bug

#2720 doc: update windows `-fstack-clash-protection` doc
  configure.ac
Labels: build system, compatibility

#2725 diag: fix researcher mode check
  src/wallet/diagnose.h
Labels: bug

#2727 ci: do not silently fail
  ci/test_run_all.sh
Labels: enhancement, build system

#2728 gui: Add missing switch cases for ALREADY_IN_MEMPOOL
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: bug, gui

#2729 serialize: allow variants to be serialized
  src/serialize.h
  src/test/serialize_tests.cpp
Labels: enhancement

#2730 Properly include Boost Array header
  src/wallet/diagnose.h
  test/lint/lint-includes.sh
Labels: compatibility
