Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2023-01, with the labels that each got.

#2612 ARMv8 SHA2 Intrinsics
  configure.ac
  src/Makefile.am
  src/crypto/sha256.cpp
  src/crypto/sha256_arm_shani.cpp
  src/crypto/sha256_x86_shani.cpp
Labels: enhancement, build system

#2621 rpc: Repair auditsnapshotaccrual rpc function
  src/netaddress.h
  src/rpc/mining.cpp
Labels: bug, rpc

#2624 gui, voting: Update pool cpids and avw rules
  src/gridcoin/researcher.h
  src/gridcoin/voting/poll.cpp
Labels: gui, Polls

#2625 scraper, gui: Add external adapter projects indication
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper.h
  src/qt/researcher/researchermodel.cpp
Labels: enhancement, gui

#2626 ci: bump python and setup-python action version
  .github/workflows/ci.yml
Labels: build system, compatibility

#2622 gui: Correct updateBeaconIcon() function in bitcoingui.cpp
  src/qt/bitcoingui.cpp
  src/qt/researcher/researchermodel.cpp
  src/qt/researcher/researchermodel.h
Labels: bug, gui

#2628 gui: implement INSUFFICIENT_MATURE_FUNDS status for the mrcmodel
  src/qt/mrcmodel.cpp
  src/qt/mrcmodel.h
  src/qt/mrcrequestpage.cpp
Labels: enhancement, gui

#2627 wallet: Strengthen CWalletTx::RevalidateTransactions
  src/wallet/wallet.cpp
Labels: bug

#2632 test: Fix Wambiguous-reversed-operator compiler warning, drop boost::assign
  src/test/multisig_tests.cpp
  src/test/serialize_tests.cpp
  test/lint/lint-includes.sh
Labels: compatibility, deprecation

#2633 gui: Change text from username to name (real name or nickname)
  src/qt/forms/researcherwizardauthpage.ui
Labels: bug, gui
