Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2024-03, with the labels that each got.

#2745 translations: translation updates for Miss Piggy release
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_pt_PT.ts
  src/qt/locale/bitcoin_vi.ts
Labels: translations

#2741 build: Implement comp_double comparison function in certain tests
  src/test/gridcoin/claim_tests.cpp
  src/test/gridcoin/researcher_tests.cpp
Labels: bug, build system

#2748 util: Adjust Fraction class addition overload overflow tests
  src/test/util_tests.cpp
  src/util.h
Labels: bug

#2747 build, depends: fix compilation with XCode 15
  configure.ac
  depends/packages/boost.mk
  depends/packages/libzip.mk
  depends/packages/qt.mk
  depends/patches/qt/fix-macos-linker.patch
Labels: build system, compatibility

#2746 build: enforce SSE2 on x86 targets
  configure.ac
  src/test/gridcoin/claim_tests.cpp
  src/test/gridcoin/researcher_tests.cpp
Labels: bug, build system

#2751 net, consensus: Ban nodes 5.4.5.0 and below
  src/main.cpp
Labels: bug, mandatory

#2749 Fix man page installation path for cmake builds
  src/CMakeLists.txt
  src/qt/CMakeLists.txt
Labels: build system, compatibility

#2553 build: add option for sanitizers
  .github/workflows/ci.yml
  ci/test/00_setup_env_native_asan.sh
  ci/test/00_setup_env_native_tsan.sh
  ci/test/04_install.sh
  configure.ac
  src/Makefile.am
  src/consensus/merkle.cpp
  src/consensus/merkle.h
  src/gridcoin/cpid.h
  src/gridcoin/mrc.h
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoin/superblock.cpp
  src/main.h
  src/miner.cpp
  src/support/lockedpool.cpp
  src/test/accounting_tests.cpp
  src/test/gridcoin/beacon_tests.cpp
  src/test/gridcoin/cpid_tests.cpp
  src/test/gridcoin/mrc_tests.cpp
  src/test/gridcoin/superblock_tests.cpp
  src/test/merkle_tests.cpp
  src/test/test_gridcoin.cpp
  src/test/transaction_tests.cpp
  src/test/util_tests.cpp
  src/test/wallet_tests.cpp
  src/util/strencodings.cpp
  test/sanitizer_suppressions/lsan
  test/sanitizer_suppressions/tsan
  test/sanitizer_suppressions/ubsan
Labels: enhancement, build system

#2754 Fix Systemd unit install location
  src/CMakeLists.txt
Labels: bug, build system

#2733 build: CMake: Initial Windows support (MSYS2)
  .github/workflows/cmake-ci.yml
  CMakeLists.txt
  build-aux/cmake/Hunter/config.cmake
  build-aux/cmake/HunterGate.cmake
  doc/README.md
  doc/build-msys2.md
  doc/build-windows.md
  doc/cmake-options.md
  src/CMakeLists.txt
  src/bdb53/CMakeLists.txt
  src/crypto/CMakeLists.txt
  src/qt/CMakeLists.txt
  src/qt/test/CMakeLists.txt
  src/test/CMakeLists.txt
Labels: enhancement, build system

#2755 scraper: Corrections to scraper_net after removal of cntPartsRcvd decrement and increment
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/scraper/scraper_net.cpp
  src/gridcoin/scraper/scraper_net.h
Labels: bug

#2753 consensus, mrc, sidestake: add mrc fees to staker to rewards to be allocated via sidestaking
  src/gridcoin/sidestake.cpp
  src/gridcoin/sidestake.h
  src/miner.cpp
  src/miner.h
  src/rpc/blockchain.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/test/gridcoin/mrc_tests.cpp
Labels: bug, mandatory
