Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2024-06, with the labels that each got.

#2769 build: explicitly include FindPkgConfig for CMake
  CMakeLists.txt
Labels: build system

#2767 [cmake] bdb53: disable error for implicit-int with gcc
  configure.ac
  src/bdb53/CMakeLists.txt
Labels: build system, compatibility

#2768 rpc/server: fix removing deprecated commands from command list
  src/rpc/server.cpp
Labels: bug
