Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2024-02, with the labels that each got.

#2735 util: Enhance Fraction class overflow resistance
  src/test/util_tests.cpp
  src/util.h
Labels: enhancement

#2731 beacon, registry: Fix beacon history stall
  src/chainparams.h
  src/gridcoin/beacon.cpp
  src/gridcoin/beacon.h
  src/gridcoin/contract/registry_db.h
  src/gridcoin/project.cpp
  src/gridcoin/project.h
  src/gridcoin/protocol.cpp
  src/gridcoin/protocol.h
  src/gridcoin/scraper/scraper_registry.cpp
  src/gridcoin/scraper/scraper_registry.h
  src/gridcoin/sidestake.cpp
  src/gridcoin/sidestake.h
  src/gridcoin/tally.cpp
  src/qt/mrcmodel.cpp
  src/rpc/mining.cpp
  src/test/gridcoin/beacon_tests.cpp
Labels: bug, refactor, test suite

#2737 refactor: Fix compilation warnings
  src/alert.cpp
  src/alert.h
  src/gridcoin/beacon.cpp
  src/gridcoin/contract/registry_db.h
  src/gridcoin/gridcoin.cpp
  src/gridcoin/md5.c
  src/gridcoin/mrc.cpp
  src/gridcoin/quorum.cpp
  src/gridcoin/scraper/http.cpp
  src/gridcoin/scraper/scraper.cpp
  src/gridcoin/sidestake.h
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/result.cpp
  src/miner.cpp
  src/net.cpp
  src/qt/addressbookpage.h
  src/qt/guiutil.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/voting/additionalfieldstablemodel.cpp
  src/qt/voting/additionalfieldstablemodel.h
  src/qt/voting/polltab.cpp
  src/qt/voting/polltablemodel.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/pollwizarddetailspage.cpp
  src/qt/walletmodel.h
  src/random.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
  src/script.cpp
  src/test/dos_tests.cpp
  src/test/gridcoin/project_tests.cpp
  src/test/script_tests.cpp
  src/test/wallet_tests.cpp
  src/test/xxd/xxd.c
  src/util.h
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.h
  test/lint/lint-spelling.ignore-words.txt
Labels: build system, compatibility, refactor

#2740 util: Improve allocation class
  src/gridcoin/sidestake.cpp
  src/gridcoin/sidestake.h
  src/miner.cpp
  src/test/gridcoin/sidestake_tests.cpp
  src/test/wallet_tests.cpp
  src/validation.cpp
Labels: bug, enhancement

#2738 gui, util: Improve upgrade dialog
  src/Makefile.qt.include
  src/gridcoin/upgrade.cpp
  src/gridcoin/upgrade.h
  src/node/ui_interface.cpp
  src/node/ui_interface.h
  src/noui.cpp
  src/qt/CMakeLists.txt
  src/qt/aboutdialog.cpp
  src/qt/aboutdialog.h
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/aboutdialog.ui
  src/qt/forms/updatedialog.ui
  src/qt/updatedialog.cpp
  src/qt/updatedialog.h
  src/qt/upgradeqt.cpp
  src/wallet/diagnose.h
Labels: enhancement, gui

#2743 ci: change Qt path in CMake CI
  .github/workflows/cmake-ci.yml
Labels: bug

#2744 net: Correct -tor argument handling
  src/init.cpp
Labels: bug

#2742 gui: Implement poll field length limiters in GUI forms
  src/gridcoin/voting/builders.cpp
  src/gridcoin/voting/poll.h
  src/qt/voting/pollwizarddetailspage.cpp
  src/qt/voting/pollwizardprojectpage.cpp
  src/qt/voting/votingmodel.cpp
  src/qt/voting/votingmodel.h
Labels: bug, gui
