Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2025-06, with the labels that each got.

#2811 gui: This fixes the logic for display of projects that require external adapters
  src/qt/researcher/researchermodel.cpp
Labels: bug, gui

#2798 qt, build, ci: add optional Qt 6 support
  .github/workflows/cmake-ci.yml
  CMakeLists.txt
  share/qt/Info.plist.cmake.in
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/addressbookpage.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoinunits.h
  src/qt/coincontroldialog.cpp
  src/qt/consolidateunspentwizardselectinputspage.cpp
  src/qt/diagnosticsdialog.h
  src/qt/guiutil.cpp
  src/qt/overviewpage.cpp
  src/qt/peertablemodel.cpp
  src/qt/rpcconsole.cpp
  src/qt/test/CMakeLists.txt
  src/qt/trafficgraphwidget.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/upgradeqt.cpp
  src/qt/upgradeqt.h
  src/qt/voting/additionalfieldstablemodel.cpp
  src/qt/voting/polldetails.cpp
  src/qt/voting/pollresultchoiceitem.cpp
  src/qt/voting/polltab.cpp
  src/qt/voting/polltablemodel.h
  src/qt/voting/pollwizarddetailspage.cpp
  src/qt/voting/votingmodel.h
  src/qt/winshutdownmonitor.cpp
  src/qt/winshutdownmonitor.h
Labels: build system, compatibility

#2813 scraper: Change scraper_net unserialize check to include ALL_BUT_DELETED projects
  src/gridcoin/scraper/scraper_net.cpp
Labels: bug

#2815 documentation: fix some minor issues in the comments
  src/gridcoin/project.h
  src/gridcoin/voting/poll.cpp
Labels: documentation
