Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2025-02, with the labels that each got.

#2791 doc: cmake is required for Windows depends
  doc/build-windows.md
Labels: build system, documentation

#2792 poll, gui: Disable choice add button in poll wizard when choice limit is reached
  src/qt/voting/pollwizarddetailspage.cpp
Labels: bug, gui

#2793 build: omit _FORTIFY_SOURCE on debug
  configure.ac
Labels: enhancement, build system
