Repository gridcoin-community/Gridcoin-Research, pull requests merged in 2025-07, with the labels that each got.

#2816 bdb53: Update embedded bdb53 code for gcc15+
  src/bdb53/src/env/env_config.c
Labels: build system, compatibility

#2814 gui, init: Fixes the 'Blocks Verified' message total
  src/dbwrapper.cpp
Labels: bug

#2817 autogreylist: Removes zcd, was, and meets greylist criteria from getautogreylist history
  src/gridcoin/project.h
  src/rpc/blockchain.cpp
Labels: enhancement
